### ISSUE TITLE
[Feature Request] Chrome Tabs

### ISSUE THREAD

**Issue by jerryn70** [ZeeRooo/MaterialFBook#103]
Use custom chrome tabs for external links. If you using XDA labs then you will understand what I mean. 

The main reason I use browsers for browsing fb is , when I see an interesting topic i will open that in an background tab and continues reading news feeds then later I will come back an switch tab and read that topic

**Comment by panic175** [comment]
+1

**Comment by ZeeRooo** [comment]
Is better use the default browser.
Its a waste of space if the user don't have Chrome installed.

**Comment by jerryn70** [comment]
For chrome like tabs we don't need to install chrome browser.  I don't have chrome installed on my device but I can use chrome tabs like feature in XDA labs .

**Comment by panic175** [comment]
Firefox uses the api too...
