### ISSUE TITLE
Hide bottom bar

### ISSUE THREAD

**Issue by lfom** [ZeeRooo/MaterialFBook#105]
Hello! The app works pretty good but the bottom bar hides some of the content, making it impossible to click/read sometimes. Either hide it while scrolling down like some mobile browsers do, or simply move the buttons to the top bar (I think the name there is kinda useless). Thanks!

**Comment by panic175** [comment]
+1

**Comment by davidmef** [comment]
+1

**Comment by ZeeRooo** [comment]
Yes, i know the beta sucks. Just downgrade to the latest stable version.
Sorry.

**Comment by lfom** [comment]
@ZeeRooo No, it's great! Just need to work the bottom bar, and notifications seem flaky (I don't get them). I've tried 3.4.5 but if force quits in background so I went back to B-3.5. Regards

**Comment by PHPCEO** [comment]
+1

**Comment by callegar** [comment]
Same here. Biggest issue is that it does not let you edit comments. Please, consider asking fdroid not to mark beta versions as recommended upgrades.

**Comment by callegar** [comment]
Same here. Biggest issue is that it does not let you edit comments. Please, consider asking fdroid not to mark beta versions as recommended upgrades.

**Comment by fabmazz** [comment]
This also hides messages while I'm writing, I literally can't see what I'm writing XD. Maybe you could hide the bottom bar while the keyboard is open
