### ISSUE TITLE
not working on android 4.4.2

### ISSUE THREAD

**Issue by 1karlhe** [ZeeRooo/MaterialFBook#107]
Hi, i cant open the lastest versión of the app (3.5.0) on a phone with android 4.4.2 i constantly get unexpected error when trying to open, it wont even show the log un screen. Versión 3.4.5 works fine and currently using it. I dont know any programing so i dont know how to send a bug report for this sorry.

**Comment by ZeeRooo** [comment]
Please try with the new versión. https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_3.6.0.apk?raw=true

Let me know if i can close the issue.

**Comment by ZeeRooo** [comment]
Ok, now its working on JB and KitKat as expected. 
I will close this issue.
