### ISSUE TITLE
Images in albums load in very low quality

### ISSUE THREAD

**Issue by Poomex** [ZeeRooo/MaterialFBook#108]
When trying to load a big album (17 photos), images load in extremely low, grainy quality, making them illegible. It seems that when I load further images have better quality, however still low.

**Comment by ZeeRooo** [comment]
Yes, i know. This is a issue from facebook mobile site, no only the app.
If you check an album from m.facebook.com you'll see it's in a very low quality.
PS: Sorry for the late response.
