### ISSUE TITLE
Dark Theme Is Too Dark.. 

### ISSUE THREAD

**Issue by ibuprophen1** [ZeeRooo/MaterialFBook#110]
The Dark Theme reflects items that are way too dark and hard to see the images within them.

An example of this is reflected on the attached image. 

[dark-theme-example-image](https://user-images.githubusercontent.com/18060271/31309544-da590ce4-ab55-11e7-88ab-a7afa8fac427.jpg)

Thanks!

**Comment by ibuprophen1** [comment]
Closed due to unanswered issue after 10 weeks... 

Thank you very much :-)

**Comment by ZeeRooo** [comment]
I dont think it's a bug, it's a black theme... If the bar is blue i'll be
ugly imho
