### ISSUE TITLE
Option to hide News Feed

### ISSUE THREAD

**Issue by gustavo-hms** [ZeeRooo/MaterialFBook#12]
Face Slim (https://github.com/indywidualny/FaceSlim) has an option to hide the News Feed entirely. It's useful when you don't want or can't spend to much time on Facebook. I'm quite used to this option (I even use a Firefox add-on to do the same: https://addons.mozilla.org/firefox/addon/hide-facebook-feed), but your app is much better than Face Slim, so I would like to migrate to it.

**Comment by ZeeRooo** [comment]
This feature was added in v2.1.0 :) 
Enjoy.

**Comment by gustavo-hms** [comment]
Great! Thank you.
