### ISSUE TITLE
Repeated crashing while and not running in foreground

### ISSUE THREAD

**Issue by theauditor** [ZeeRooo/MaterialFBook#120]
Been running the app for some three days now on my Mi A1 with Android N. 
The app has crashed repeatedly some 30 plus times, while I was using it and while it was in the background. 

Was unable to find a crash report or log, If there is one just let me know, will add it.

Replication -

1. Install and log in to account
2. Browse or leave it alone for some time
3. Switch to some other app and wait
or
4. Just keep browsing for some time

**Comment by ZeeRooo** [comment]
Sorry but i couldn't work on the app for my exams + computer.
But now it's fixed. If you want, check the last versión.
https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_3.6.0.apk?raw=true
