### ISSUE TITLE
Crash pausing main activity.

### ISSUE THREAD

**Issue by creativetrendsapps** [ZeeRooo/MaterialFBook#121]
There's a crash when pausing the app in main activity, only when a used is logged in.

**Comment by ZeeRooo** [comment]
Yes. The first time (no cookies)
I forget the conditional to stop the handler.
Tomorrow i'll upload a fixed version.

**Comment by creativetrendsapps** [comment]
This happens when there is a cookie. However it's this line  badgeUpdate.removeCallbacks(badgeTask);
    }

**Comment by ZeeRooo** [comment]
`if (badgeTask != null && badgeUpdate != null)
            badgeUpdate.removeCallbacks(badgeTask);`

This solve the issue.

**Comment by creativetrendsapps** [comment]
As the commit was closed, I'll close this issue for you.

**Comment by ZeeRooo** [comment]
Ok, thank you Jorell!
