### ISSUE TITLE
Playing videos doesn't work

### ISSUE THREAD

**Issue by alekksander** [ZeeRooo/MaterialFBook#122]
on one of my devices (on other phone it works) playing facebook videos doesn't work. clean install didn't help. i click on the video, the player shows up in fullscreen, but nothing is there, just black static and video controls. this was a problem in 3.4.1 too (didn't check previous versions)

**Comment by creativetrendsapps** [comment]
@alekksander what OS version is your device that _Playing videos doesn't work on?_

**Comment by alekksander** [comment]
android 5.1

**Comment by ZeeRooo** [comment]
@alekksander Please tell me if the issue continue after the 3.6.1.
Im trying different videos and worked (im on 5.1 too).

**Comment by alekksander** [comment]
Yes, its exactly the same.

**Comment by ZeeRooo** [comment]
Mmm maybe is a heavy video, i dont know.
I'm downloading KitKat image for emulator, i'll try the videos on different versions.

**Comment by alekksander** [comment]
Please don't. The problem here is NetGuard. Even mfb is allowed to acces the connection, video wont start

**Comment by ZeeRooo** [comment]
No, MFB uses a custom player.
Here's the code of the player activity; https://github.com/ZeeRooo/MaterialFBook/blob/master/app/src/main/java/me/zeeroooo/materialfb/Activities/Video.java

I'll check NetGuard late. It's an advance, isn't necessary start from scratch xD

**Comment by ZeeRooo** [comment]
I'm playing a video while NetGuard is running. Can you tell me your NetGuard configuration to test it?
Look: https://i.imgur.com/hdpTY0y.png

**Comment by alekksander** [comment]
could You block everything except mfb and try then?

**Comment by alekksander** [comment]
here are exported settings from NetGuard: (these have to be saved as .xml before importing in NetGuard)
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<netguard>
  <application>
    <setting key="hint_push" type="boolean" value="false" />
    <setting key="admob" type="boolean" value="true" />
    <setting key="show_top" type="boolean" value="false" />
    <setting key="subnet" type="boolean" value="true" />
    <setting key="lockdown_other" type="boolean" value="true" />
    <setting key="unmetered_2g" type="boolean" value="false" />
    <setting key="version" type="integer" value="2017112801" />
    <setting key="hint_system" type="boolean" value="false" />
    <setting key="tethering" type="boolean" value="true" />
    <setting key="screen_wifi" type="boolean" value="false" />
    <setting key="lan" type="boolean" value="true" />
    <setting key="wifi_homes" type="set" value="" />
    <setting key="whitelist_wifi" type="boolean" value="true" />
    <setting key="disable_on_call" type="boolean" value="false" />
    <setting key="hint_whitelist" type="boolean" value="false" />
    <setting key="show_system" type="boolean" value="true" />
    <setting key="pcap_record_size" type="string" value="64" />
    <setting key="log_app" type="boolean" value="false" />
    <setting key="national_roaming" type="boolean" value="true" />
    <setting key="ip6" type="boolean" value="true" />
    <setting key="reload_onconnectivity" type="boolean" value="true" />
    <setting key="screen_on" type="boolean" value="true" />
    <setting key="eu_roaming" type="boolean" value="false" />
    <setting key="use_metered" type="boolean" value="false" />
    <setting key="hint_usage" type="boolean" value="false" />
    <setting key="hosts_url" type="string" value="https://www.netguard.me/hosts" />
    <setting key="socks5_enabled" type="boolean" value="false" />
    <setting key="update_check" type="boolean" value="false" />
    <setting key="sort" type="string" value="name" />
    <setting key="use_hosts" type="boolean" value="true" />
    <setting key="debug_iab" type="boolean" value="false" />
    <setting key="filter" type="boolean" value="false" />
    <setting key="notify_access" type="boolean" value="false" />
    <setting key="dark_theme" type="boolean" value="false" />
    <setting key="enabled" type="boolean" value="true" />
    <setting key="lockdown_wifi" type="boolean" value="true" />
    <setting key="pcap_file_size" type="string" value="2" />
    <setting key="auto_enable" type="string" value="0" />
    <setting key="show_stats" type="boolean" value="false" />
    <setting key="whitelist_roaming" type="boolean" value="false" />
    <setting key="screen_delay" type="string" value="0" />
    <setting key="initialized" type="boolean" value="true" />
    <setting key="debug_ads" type="boolean" value="false" />
    <setting key="App Restrictions" type="string" value="AAAAAA==&#10;" />
    <setting key="track_usage" type="boolean" value="false" />
    <setting key="stats_samples" type="string" value="90" />
    <setting key="whitelist_other" type="boolean" value="true" />
    <setting key="stats_frequency" type="string" value="1000" />
    <setting key="clear_onreload" type="boolean" value="false" />
    <setting key="unmetered_4g" type="boolean" value="false" />
    <setting key="watchdog" type="string" value="0" />
    <setting key="install" type="boolean" value="false" />
    <setting key="screen_other" type="boolean" value="false" />
    <setting key="show_nointernet" type="boolean" value="false" />
    <setting key="manage_system" type="boolean" value="true" />
    <setting key="loglevel" type="string" value="6" />
    <setting key="lockdown" type="boolean" value="false" />
    <setting key="theme" type="string" value="teal" />
    <setting key="unmetered_3g" type="boolean" value="false" />
  </application>
  <wifi>
    <setting key="com.adam.aslfms" type="boolean" value="false" />
    <setting key="com.google.android.gms" type="boolean" value="true" />
    <setting key="com.google.android.backuptransport" type="boolean" value="true" />
    <setting key="me.zeeroooo.materialfb" type="boolean" value="false" />
    <setting key="com.google.android.apps.maps" type="boolean" value="false" />
    <setting key="com.android.providers.downloads.ui" type="boolean" value="false" />
    <setting key="cgeo.geocaching" type="boolean" value="false" />
    <setting key="root" type="boolean" value="true" />
    <setting key="link.standen.michael.phonesaver" type="boolean" value="false" />
    <setting key="com.github.yeriomin.yalpstore" type="boolean" value="false" />
    <setting key="com.redbend.client" type="boolean" value="false" />
    <setting key="fr.kwiatkowski.ApkTrack" type="boolean" value="false" />
    <setting key="com.vonglasow.michael.satstat" type="boolean" value="false" />
    <setting key="me.zeerooo.materialfb" type="boolean" value="false" />
    <setting key="com.google.android.stardroid" type="boolean" value="false" />
    <setting key="com.android.providers.media" type="boolean" value="false" />
    <setting key="org.lichess.mobileapp" type="boolean" value="false" />
    <setting key="org.schabi.newpipe" type="boolean" value="false" />
    <setting key="com.biglybt.android.client" type="boolean" value="false" />
    <setting key="com.SecUpwN.AIMSICD" type="boolean" value="false" />
    <setting key="org.openobservatory.ooniprobe" type="boolean" value="false" />
    <setting key="com.mendhak.gpslogger" type="boolean" value="false" />
    <setting key="com.android.providers.downloads" type="boolean" value="false" />
  </wifi>
  <mobile>
    <setting key="com.adam.aslfms" type="boolean" value="false" />
    <setting key="com.google.android.backuptransport" type="boolean" value="true" />
    <setting key="com.google.android.gms" type="boolean" value="true" />
    <setting key="me.zeeroooo.materialfb" type="boolean" value="false" />
    <setting key="com.google.android.apps.maps" type="boolean" value="false" />
    <setting key="com.android.providers.downloads.ui" type="boolean" value="false" />
    <setting key="cgeo.geocaching" type="boolean" value="false" />
    <setting key="root" type="boolean" value="true" />
    <setting key="link.standen.michael.phonesaver" type="boolean" value="false" />
    <setting key="com.github.yeriomin.yalpstore" type="boolean" value="false" />
    <setting key="com.redbend.client" type="boolean" value="false" />
    <setting key="fr.kwiatkowski.ApkTrack" type="boolean" value="false" />
    <setting key="com.vonglasow.michael.satstat" type="boolean" value="false" />
    <setting key="me.zeerooo.materialfb" type="boolean" value="false" />
    <setting key="com.google.android.stardroid" type="boolean" value="false" />
    <setting key="org.lichess.mobileapp" type="boolean" value="false" />
    <setting key="com.android.providers.media" type="boolean" value="false" />
    <setting key="org.schabi.newpipe" type="boolean" value="false" />
    <setting key="com.biglybt.android.client" type="boolean" value="false" />
    <setting key="com.SecUpwN.AIMSICD" type="boolean" value="false" />
    <setting key="org.openobservatory.ooniprobe" type="boolean" value="false" />
    <setting key="com.mendhak.gpslogger" type="boolean" value="false" />
    <setting key="com.android.providers.downloads" type="boolean" value="false" />
  </mobile>
  <screen_wifi>
    <setting key="com.redbend.client" type="boolean" value="true" />
    <setting key="com.brave.browser" type="boolean" value="true" />
    <setting key="fr.kwiatkowski.ApkTrack" type="boolean" value="true" />
    <setting key="com.vonglasow.michael.satstat" type="boolean" value="true" />
    <setting key="com.eolwral.osmonitor" type="boolean" value="true" />
    <setting key="com.fastaccess.github" type="boolean" value="true" />
    <setting key="org.mozilla.fennec_aurora" type="boolean" value="true" />
    <setting key="net.etuldan.sparss.floss" type="boolean" value="true" />
    <setting key="jp.hazuki.yuzubrowser" type="boolean" value="true" />
    <setting key="com.pitchedapps.frost" type="boolean" value="true" />
    <setting key="me.zeeroooo.materialfb" type="boolean" value="true" />
    <setting key="com.a5corp.weather" type="boolean" value="true" />
    <setting key="cgeo.geocaching" type="boolean" value="true" />
    <setting key="pl.orange.mojeorange" type="boolean" value="true" />
    <setting key="fr.ornidroid" type="boolean" value="true" />
    <setting key="com.google.earth" type="boolean" value="true" />
    <setting key="com.llamacorp.equate" type="boolean" value="true" />
    <setting key="net.osmand" type="boolean" value="true" />
    <setting key="com.SecUpwN.AIMSICD" type="boolean" value="true" />
    <setting key="com.github.yeriomin.yalpstore" type="boolean" value="true" />
  </screen_wifi>
  <screen_other>
    <setting key="com.brave.browser" type="boolean" value="true" />
    <setting key="com.redbend.client" type="boolean" value="true" />
    <setting key="fr.kwiatkowski.ApkTrack" type="boolean" value="true" />
    <setting key="com.vonglasow.michael.satstat" type="boolean" value="true" />
    <setting key="com.eolwral.osmonitor" type="boolean" value="true" />
    <setting key="com.fastaccess.github" type="boolean" value="true" />
    <setting key="org.mozilla.fennec_aurora" type="boolean" value="true" />
    <setting key="net.etuldan.sparss.floss" type="boolean" value="true" />
    <setting key="jp.hazuki.yuzubrowser" type="boolean" value="true" />
    <setting key="com.pitchedapps.frost" type="boolean" value="true" />
    <setting key="me.zeeroooo.materialfb" type="boolean" value="true" />
    <setting key="com.a5corp.weather" type="boolean" value="true" />
    <setting key="cgeo.geocaching" type="boolean" value="true" />
    <setting key="pl.orange.mojeorange" type="boolean" value="true" />
    <setting key="fr.ornidroid" type="boolean" value="true" />
    <setting key="com.google.earth" type="boolean" value="true" />
    <setting key="com.llamacorp.equate" type="boolean" value="true" />
    <setting key="net.osmand" type="boolean" value="true" />
    <setting key="com.SecUpwN.AIMSICD" type="boolean" value="true" />
    <setting key="com.github.yeriomin.yalpstore" type="boolean" value="true" />
  </screen_other>
  <roaming />
  <lockdown />
  <apply />
  <notify />
  <filter />
  <forward />
</netguard>`

**Comment by alekksander** [comment]
I'm wondering if it's MFB client problem, or rather NetGuard (as it appears for my unexperienced eye). What do You think about reporting this thread on NetGuard's XDA forum?

**Comment by ZeeRooo** [comment]
Ok. I have imported your settings and it still working for me. I'll try on different android versions.
At the beginning, NetGuard says "this app doesn't work on ALL devices", maybe this is a case.

**Comment by alekksander** [comment]
How about if You check in setting to block everything by default, and then manually allow MFB to access?

**Comment by M66B** [comment]
This issue should be closed, see here: https://forum.xda-developers.com/showpost.php?p=74863118&postcount=5896
