### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by alekksander** [ZeeRooo/MaterialFBook#123]
Fresh install version 3.6 — search doesn't work. upper bar appears (sometimes it doesn't appear if im at the bottom of page i guess), and when enter is pressed it redirects to fb page saying „Sorry, something went wrong”

**Comment by ZeeRooo** [comment]
When it doesnt appear you have to scroll to the top and you'll see the
toolbar.
But i have tryied the search engine in Lollipop and JB 4.2 and works.
Please tell me your android version.

**Comment by alekksander** [comment]
5.1

**Comment by ZeeRooo** [comment]
It's my moto x version and is working (wrong warning appear only if i wrote
anything unusual like "jdjdbsj"). Anyway creativetrends commited an url
change in the search, maybe it'll works. Later i'll upload a new version
with fixes

**Comment by ZeeRooo** [comment]
Fixed. https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_v3.6.1.apk?raw=true

**Comment by alekksander** [comment]
okay, so turns out it couldn't „understand” polish surnames :smile:

**Comment by ZeeRooo** [comment]
Wait a minute. I forget something. Im uploading it again xD

**Comment by alekksander** [comment]
ps. have You seen gui of foss app called fasthub? perhaps it's something You may think about :wink:

**Comment by ZeeRooo** [comment]
Sorry for the mistake xD. Here's the link: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_v3.6.1.apk?raw=true
FastHub looks great for anyone who use all the time Github.

**Comment by alekksander** [comment]
i remember You were experimenting with lower bar etc, fasthub might be an inspiration maybe
Thank You for corrected version :)

**Comment by ZeeRooo** [comment]
Ohh you are right. But the navigation drawer is better (more options, more
space on the screen) and the users prefer it instead of the tabs.
