### ISSUE TITLE
force closeing on its own

### ISSUE THREAD

**Issue by oakes8585** [ZeeRooo/MaterialFBook#138]
Im running a nexus 6 with a custom rooted rom and have never had any app issues. Now with that being said so far i love this app only issue i have is about every 3rd or fourth time i open the app it will quit working and force close..... any ideas??

**Comment by ZeeRooo** [comment]
Hmm.. i recently experienced similar issues but i dont know what it is because i was on the school and i couln't see the logcat. _Maybe_ they are caused by the notifications timeout (the slow internet reach the JSoup timeout and throw an exception = fc).

**Comment by alekksander** [comment]
Still happening in 3.7.0. App quits for no apparent reason.
