### ISSUE TITLE
no articles could be seen; 2.1.0

### ISSUE THREAD

**Issue by dklueh79** [ZeeRooo/MaterialFBook#14]
Since upgrading to 2.1.0, I couldn't see any postings etc. Only notifications and friends work

**Comment by dklueh79** [comment]
"Hide news feed" is already disabled. No article is shown, no top and no recent news. 
Only my header is shown

**Comment by dklueh79** [comment]
"Hide news feed" is already disabled. No article is shown, no top and no recent news. 
Only my header is shown.

Partially solved: once deactivated, the switched on and again off. Now knews are shown...

**Comment by ZeeRooo** [comment]
Enable, close the app, enter again and disable. Then go back and refresh.
