### ISSUE TITLE
Now Loading In Low Data Mode All The Time

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#141]
All of a sudden all pages are loading in Low Data Mode.

I uninstalled and reinstalled and reset all settings, it did nothing.

I think facebook changed something and broke MaterialFBook...

**Comment by creativetrendsapps** [comment]
Facebook changed something that affects the User Agent. I've submitted a pull request. Hopefully, @ZeeRooo can implement it, or another user agent soon.

**Comment by ZeeRooo** [comment]
What the hell Facebook...
I have fixed it in the 3.7.5.
Thanks guys

**Comment by Jotam** [comment]
You're champs!
