### ISSUE TITLE
Copy of your app on Google Play (Copyright violation)

### ISSUE THREAD

**Issue by Poussinou** [ZeeRooo/MaterialFBook#143]
Hi @ZeeRooo 

I found [this app](https://play.google.com/store/apps/details?id=lite.messenger.litefacebook) and also [this one](https://play.google.com/store/apps/details?id=messenger.facebooklite.messengerforfacebook) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copies from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The original app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by creativetrendsapps** [comment]
@Poussinou , the first link is technically ok as they've provided credits, just missing the source code.

**Comment by ZeeRooo** [comment]
Ohh thanks for share!
He wrote the credits in the description, so it's ok for me. He forgot to
put the source code, but i did some "ilegal" things in the past too (when i
started the project) so i feel that i can't say anything about it.

**Comment by Poussinou** [comment]
Yes, they miss the source code, something very important for me... Do what you want, if it's OK for you ;)

**Comment by Poussinou** [comment]
The copycats have been removed. Please report here if you find other copies 👍
