### ISSUE TITLE
Can't access messages with latest build

### ISSUE THREAD

**Issue by singulararmchair** [ZeeRooo/MaterialFBook#145]
When trying to access my messages, I just reach a page that tells me to install Messenger.

Also, older builds suddenly started looking weird. 
Everything is suddenly left-aligned, vertical spacing virtually gone. Can still access messages, but it's quite unpleasant to navigate.

**Comment by ZeeRooo** [comment]
Ohh damn facebook...
The old useragent is no longer supported and the ads return... I'll fix it
today.

**Comment by dmillerzx** [comment]
Confirming the same, the latest released version of fdroid started showing text all janky which led me to grab the latest apk from GitHub.  As reported attempting to message force closes the app. Do you plan to continue updating on fdroid?  The latest released there is two revs old iirc.  Thanks for the great app!!

**Comment by Jotam** [comment]
Same problem here. In fact, when I try to access messages, the app crashes and force closes with no error notification at all. Still, thank you for this amazing app and for keeping things up-to-date at an amazing speed!

**Comment by falferezg** [comment]
Same problem here. In fact, when I try to access messages, the app crashes and force closes with no error notification at all. Thank you for this great app!

**Comment by ZeeRooo** [comment]
Can anyone tell me in which android version the app crashes? i'll try to replicate the error.

**Comment by dmillerzx** [comment]
3.7.5 app crashes when attempting to view messages.

**Comment by dmillerzx** [comment]
Sorry didn't read... :P. I'm on 8.1 April security update OG Pixel XL

**Comment by Jotam** [comment]
Android 7.1.2 (LineageOS), March security update.

**Comment by pakodx** [comment]
Android 5.1

**Comment by rabelux** [comment]
Android 6.0.1

**Comment by alekksander** [comment]
5.1 a lot, even when idle (reading article without touching screen)

**Comment by singulararmchair** [comment]
7.1.2 (LineageOS) as well

**Comment by DavidLiedke** [comment]
8.1 Google Pixel

**Comment by falferezg** [comment]
my problem is on android 7.0

**Comment by landry314** [comment]
LineageOS 14.1, android 7.1.2 with materialfbook 3.7.5. messages do not work at all and the app crashes often when you try to view messages.

**Comment by landry314** [comment]
not possible to fix? i've been using my browser on desktop mode... sucking down data way too much.

**Comment by miiichael** [comment]
Also experiencing trouble with 3.7.5, both github and f-droid versions. Android 6.0.1 on Nexus 7 (though I expect you already have enough examples by now to show that it's not (very) specific to the version of Android.

**Comment by miloskroulik** [comment]
There is a workaround in the meantime - just enable "Low data mode" and messages will be accessible.

**Comment by singulararmchair** [comment]
where are the apks now? i can't get gradle to work on my end

**Comment by singulararmchair** [comment]
thanks! new version seems to work great so far

**Comment by ZeeRooo** [comment]
@alekksander Can you use m.facebook.com with a normal browser ?

**Comment by alekksander** [comment]
@ZeeRooo 
please contact me at:
https://www.facebook.com/aleksander.bie
i will explain.

will remove this message after getting in touch

**Comment by alekksander** [comment]
i will run some tests (probably) tomorrow. i don't have access to that phone at the moment.

**Comment by alekksander** [comment]
as suggested by @ZeeRooo this got fixed by updating WebView to the latest version.
