### ISSUE TITLE
Image/video/navigation issues

### ISSUE THREAD

**Issue by pakodx** [ZeeRooo/MaterialFBook#149]
There are a bunch of issues with full size images, most of the time the app will move me to the image screen but it won't load. Sometimes it will download the image empty. Now in the latest version there's a new issue where if I try to go to the next image on a set or gallery it'll open the full-size viewer and load nothing, it happens if I click some links too, I remember mostly seeing it in links from Tumblr.
And the video progress bar now gets stuck and doesn't show how far along you are in the video, and very often the controls get hidden behind the Android UI buttons so it's impossible to interact with them.
In the previous version when I pressed return it sent me 2 screens back, now in the latest version the number seems to be either higher or just random because navigating is a mess it keeps jumping to random screens from before at random when I try to go back.

**Comment by rabelux** [comment]
Confirming the barely visible seeekbar ![Uploading 2018-04-10 09.13.01.png…]()
and the strange behaviour of the back-button. After watching a clip and still being in the video-screen, pressing the back-button seems to always direct me to the start-page

**Comment by pakodx** [comment]
Oh true, I forgot to mention that about the back button, it happens to me too. With these empty image pages it opens when I exit then it always throws me back at the start page

**Comment by creativetrendsapps** [comment]
@ZeeRooo , you should switch to Exoplayer for the video player.

**Comment by creativetrendsapps** [comment]
Well, @pakodx, @rabelux, and @ZeeRooo. I've done several pull requests to fix these issues. Hopefully, this works for you all.

**Comment by pakodx** [comment]
I forgot to add that lately there's an ad for Facebook lite that appears often on top of the page every now and then when booting the app
And it would help if it was possible to hide the group suggestions from fb, since that's something they push a lot and it's very bothersome

**Comment by pakodx** [comment]
![screenshot_2018-04-13-10-00-42](https://user-images.githubusercontent.com/38252669/38736706-4b72b15a-3f03-11e8-9185-68d6e692fefa.png)
![screenshot_2018-04-13-09-58-23](https://user-images.githubusercontent.com/38252669/38736730-5b02f120-3f03-11e8-84ca-f097ee061928.png)
![screenshot_2018-04-13-09-58-43](https://user-images.githubusercontent.com/38252669/38736748-681025f4-3f03-11e8-9027-c200a99d6dd6.png)
![screenshot_2018-04-13-10-10-17](https://user-images.githubusercontent.com/38252669/38736790-8b71e38e-3f03-11e8-9231-d8c7b7d6c3fc.png)

**Comment by creativetrendsapps** [comment]
![screenshot_2018-04-14-13-22-26](https://user-images.githubusercontent.com/14278089/38770851-2d4c4a80-3fe7-11e8-8d57-006808c62569.png)
![screenshot_2018-04-14-13-24-04](https://user-images.githubusercontent.com/14278089/38770854-339cf01a-3fe7-11e8-8718-5619bf6f2f44.png)

Well, here is a preview of the fixes I submitted by pull request. Maybe they'll be included?

**Comment by pakodx** [comment]
Oh I hope so, the black background for pictures is very good

**Comment by creativetrendsapps** [comment]
Well... I'm going to close my pull requests.

**Comment by ZeeRooo** [comment]
@creativetrendsapps I'm trying to use less libs as possible, but if the issue continue i'll merge your pull request :)

**Comment by dmillerzx** [comment]
Also cannot navigate images in 3.7.8

**Comment by Shut3n** [comment]
Version 3.8.1
Unable to view image in fullscreen mode, specially when in a post with an attached image
In multi-image post images don't scale to screen (use to show bigger out screen limits)
Would be nice a long press option with a dialog for toggle between fullscreen view/save/reshare)
