### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by pakodx** [ZeeRooo/MaterialFBook#157]
For over a year now I haven't been getting push notifications anymore from the app, I have notifications enabled on both the app and the phone.
I have 2 installations of the app, the latest and an older one and neither of them gives me the notifications
I have to check the app myself to see if I have any new friend request/notification/message

**Comment by joakim5937x** [comment]
+1

**Comment by ZeeRooo** [comment]
Make sure that "display ntification" is enabled in the device settings
(Oreo-), and set the proper values if you are in Oreo+

**Comment by pakodx** [comment]
It is enabled, I'm on Android 5.1. Also when I try to open notification settings in the latest version the app crashes.
