### ISSUE TITLE
"Check for a new version" Link is Broken

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#159]
The link from

Settings -> More and Credits -> Check for a new version

is now a dead link. It needs to be changed to:

https://github.com/ZeeRooo/MaterialFBook/releases

Oh, and while you are there, I would love to see current version information displayed in this section as well. I was looking at a friend's app to troubleshoot and I thought the current version would be there... I had to go into system settings and find it in apps to see the version she was using.

**Comment by ZeeRooo** [comment]
Fixed on v3.8.0
