### ISSUE TITLE
Setting to use tor site

### ISSUE THREAD

**Issue by betsythefc** [ZeeRooo/MaterialFBook#16]
Facebook has a .onion address, it would be great if MaterialFBook could use this to increase security. It could use Orbot to connect to the tor network (would require a proxy setting for non-rooted phones)

**Comment by ZeeRooo** [comment]
Ok, im going to work on this feature. Thank you for the idea.

**Comment by betsythefc** [comment]
FYI the url for facebook is:

https://facebookcorewwwi.onion/

**Comment by betsythefc** [comment]
And thanks!

**Comment by ZeeRooo** [comment]
Ok, it was added in v2.3.
Try it and tell me.
