### ISSUE TITLE
Wishlist: text scaling

### ISSUE THREAD

**Issue by zerodogg** [ZeeRooo/MaterialFBook#160]
It would be really useful if a default text scale could be configured in MaterialFBook (like Face Slim has). The app text is a bit smaller than what the official fb app has, and a bit too small on my screen to be comfortable to read. In Face Slim I set the scale to 120%, which makes it much better, but I really prefer MaterialFBook. Some way to increase the font size would be greatly appreciated.

**Comment by ZeeRooo** [comment]
Added in v3.8.0

**Comment by zerodogg** [comment]
Fantastic, thanks!
