### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by briant97** [ZeeRooo/MaterialFBook#162]
No option to search Facebook exists.  Can you please add.

**Comment by ZeeRooo** [comment]
This feature already exist. Just enable it.
![screenshot_2018-04-19-22-23-24](https://user-images.githubusercontent.com/19499008/39025947-80e569c8-4420-11e8-8670-1978d5049d2f.png)

**Comment by briant97** [comment]
Awesome thanks for feedback.
