### ISSUE TITLE
More Facebook Messenger History

### ISSUE THREAD

**Issue by DanitiKain** [ZeeRooo/MaterialFBook#163]
Is there anyway to go back farther in messenger history.  I can't find older chats that were just s few days ago.  Tried the search feature and it did not show either.

**Comment by alekksander** [comment]
in messages scroll down and under last chat there is an option to see older messages. doesn't that work for You?

**Comment by briant97** [comment]
It is working now.  However when I tried I only went so far.  Works fine now.
