### ISSUE TITLE
Clicking Remote WWW Links Opens Them In Desktop Mode

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#167]
If you click a remote link that contains http://www.facebook.com/ then it opens the link in Desktop Mode instead of the Mobile Mode.

I think if MaterialFBook changes those links to http://m.facebook.com/ before executing them then it would solve this problem.

**Comment by landry314** [comment]
I think solving this issue will also solve issues #164 and #166

**Comment by sfilmak** [comment]
@ZeeRooo I think we can close this issue now

**Comment by ZeeRooo** [comment]
Sure... i had fixed it brefore broke my pc... but i couldn't upload the code xP

**Comment by landry314** [comment]
Hey, this hasn't been merged. Did you lose the code update?
