### ISSUE TITLE
Facebook page does not load

### ISSUE THREAD

**Issue by Art-2** [ZeeRooo/MaterialFBook#168]
This is what I get since version v3.7.8 
![photo_2018-04-29_19-25-01](https://user-images.githubusercontent.com/12375357/39413373-7224ae62-4be6-11e8-9223-3517442039ae.jpg)
and it's still happen in the latest version (v3.8.1)

Meanwhile, I am using the Data Saving Mode that still works.

APK from F-Droid
Android 6.0

**Comment by ZeeRooo** [comment]
Update the Android WebView

**Comment by sietsevanerve** [comment]
Hi, I experience the same issue, but Android System WebView is up-to-date on my phone. 
Android 6.1.

**Comment by Art-2** [comment]
I have updated but nothing change
