### ISSUE TITLE
Status bar color issue/glitch

### ISSUE THREAD

**Issue by abacate123** [ZeeRooo/MaterialFBook#17]
The status bar turns into a weird gray color when I enter settings menu. Android version 6.0.1 marshmallow.

See: https://tlgur.com/d/B8KJZM4o

**Comment by ZeeRooo** [comment]
Fixed in v2.3 :)

**Comment by alekksander** [comment]
yes, but not in  „more and credits” ;)

**Comment by ZeeRooo** [comment]
Omg.... Fck ZeeRooo.... Hahaha, later i upload 2.3.1

**Comment by alekksander** [comment]
Thanks!
