### ISSUE TITLE
Notifications still make sound even when "No sound" is selected in settings

### ISSUE THREAD

**Issue by LoneFenris** [ZeeRooo/MaterialFBook#170]
On version 3.8.1

**Comment by miiichael** [comment]
This may or may not be related, but the react emoji buttons recently started making noise, and I'm sure I'm not the only one keen on being able to turn this off. 😛

**Comment by ZeeRooo** [comment]
It's caused by the implementation of Notifications Channels. You have to change it from your phone's settings (Nougat+)
