### ISSUE TITLE
Update F-Droid

### ISSUE THREAD

**Issue by betsythefc** [ZeeRooo/MaterialFBook#18]
The app version in F-Droid is 2.1.0, can it be upgraded to 2.3.0?
https://f-droid.org/repository/browse/?fdfilter=materialfbook&fdid=me.zeeroooo.materialfb

**Comment by ZeeRooo** [comment]
Im not a FDroid developers. Sorry

**Comment by betsythefc** [comment]
Sorry, to clarify the version of MaterialFBook is 2.1.0, and it hasn't gotten updated to 2.3.0 in the F-Droid store. I'm not 100% sure how F-Droid does things, but I think you (as the developer of MaterialFBook) need to upload the new APK to them, is that right?

**Comment by ZeeRooo** [comment]
I dont know how F-Droid works, i dont know who upload my app to this Market, but its ok.
Ask it to: @est31 or @krt16s

**Comment by est31** [comment]
Hi @betsythefc @ZeeRooo 

The app has been updated to `2.2.0` in the repo but the builds failed because the buildserver didn't have the build tools of version `25.0.1`. The buildserver has been updated today and the next build should provide working `2.2.0` and `2.3.0` apks.

**Comment by ZeeRooo** [comment]
@est31 Thank you for the info! :)

**Comment by betsythefc** [comment]
@est31, Thanks! When should we expect the builds to be complete?

**Comment by est31** [comment]
@betsythefc somewhere in the next 1-12 hours from now

**Comment by betsythefc** [comment]
@est31, when should the new build reach F-Droid?

**Comment by est31** [comment]
@betsythefc it requires the server to be updated. I can't do anything about it sorry.

**Comment by betsythefc** [comment]
@est31, by "server to be updated" do you mean that it is now on F-Droid to build and push the update?

**Comment by est31** [comment]
@betsythefc  it has outdated tools installed https://f-droid.org/wiki/page/me.zeeroooo.materialfb/lastbuild_30

I can't update them. They will be updated, but not sure when.

**Comment by betsythefc** [comment]
@est31, Thanks for the info!
