### ISSUE TITLE
Language system isn't working

### ISSUE THREAD

**Issue by sagorahmed** [ZeeRooo/MaterialFBook#182]
When I changed the language the pages of Facebook has been changed as my selected language. But when I restart app the page of Facebook has been changed to English.
Suppose I selected Arabic from the list. After restarting the app the page of Facebook changed into English but in settings, it shows that Arabic is still the current language of this app.

#### How to reproduce

* Open and go to Settings.
* Then tap on "Change app language" option.
* Select a language.
* Get back to the main page. Make sure the page of Facebook changed as your chosen language.
* Close the app. Make sure the app is not running in the background.
* Reopen and see the Facebook language has changed to English. Then go to Settings and see your selected language is still there.
* App version: 3.8.1
* Operating system: Android 6.0.1
* Encountered Device: Galaxy A5 (2016)
https://www.youtube.com/watch?v=V6TFPKwD7B4

**Comment by ZeeRooo** [comment]
Fixed!! v3.8.6
