### ISSUE TITLE
Messenger notifications are not working - Facebook notifications are working

### ISSUE THREAD

**Issue by crok** [ZeeRooo/MaterialFBook#183]
Hi,

I'm facing the issue described in the title: Messenger notifications are not working, although Facebook notifications are working. I've checked it with all possible settings (immediate, 1min through 10mins..) but only Facebook notifications are coming up, no messenger notifications do. Probably something has been changed on Facebook's side in the site code? Is it working for everybody else? I tried it on my Redmi Note 4 Snapdragon (Mido) with [AOSP Extended 5.5 (build 20180522-1251-OFFICIAL)](https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/rom-aospextended-rom-v5-0-t3679746) and [crDroid (build 20180529 and one version before this one)](https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/rom-crdroid-v4-0-beta-t3719777) and neither are working (both are Android Oreo 8.1).

I'm not sure how can I create any kind of bug report or screenshot because it is actually not showing anything at all that is Messenger related notification - but let me know and I will do whatever is needed.

**Comment by alien2003** [comment]
the same

**Comment by crok** [comment]
Thank you - hope you closed it because it's been fixed  ( :  Will try it in next release.

**Comment by ZeeRooo** [comment]
It's. Check v3.8.6
