### ISSUE TITLE
Replace ACRA with Fabric

### ISSUE THREAD

**Issue by sfilmak** [ZeeRooo/MaterialFBook#186]
Maybe it will be a lot better to use **Fabric** instead of ACRA to receive information about each app crash - a user doesn't need to do anything after a crash, you will automatically get a report in Fabric console. 

https://get.fabric.io

**Comment by mtbu** [comment]
Fabric might also prevent distributing through F-Droid https://forum.f-droid.org/t/fabric-io-what-do-you-think/1193

**Comment by kowith337** [comment]
Fabric will soon migrated to `Google Firebase`, this is only thing i can say...
