### ISSUE TITLE
"Hide Status editor in News Feed" and "Hide Menu bar" are out of function.

### ISSUE THREAD

**Issue by DavidLiedke** [ZeeRooo/MaterialFBook#188]
App Version: 3.8.1

The function "Hide Status editor in News Feed" and "Hide Menu bar" are out of function.

![settings](https://user-images.githubusercontent.com/25581728/41806390-6931be60-76bd-11e8-8d3c-b4f2f79f2913.png)

![newsfeed](https://user-images.githubusercontent.com/25581728/41806406-b4199100-76bd-11e8-9b92-cd0b0c640ae7.png)

**Comment by ZeeRooo** [comment]
Thank you. I will fix it in the next version.
