### ISSUE TITLE
Support reading/posting on pages

### ISSUE THREAD

**Issue by Bugsbane** [ZeeRooo/MaterialFBook#190]
At the moment MaterialFBook is fabulous for reading and posting to the timeline, as well as reading and replying to messages.

It would be great if there was similar functionality to see posts done on pages the user is an admin for and to be able to reply to them / post to those pages.

Thank you!

**Comment by creativetrendsapps** [comment]
@Bugsbane ... can you do it on the Facebook mobile site?
