### ISSUE TITLE
Please add the Serbian translation

### ISSUE THREAD

**Issue by yarons** [ZeeRooo/MaterialFBook#197]
[serbian_materialfboox.xml.zip](https://github.com/ZeeRooo/MaterialFBook/files/2386356/serbian_materialfboox.xml.zip)

daimonion translated to Serbian (srpski/српски), this one is the Cyrillic version (it has a special ISO code).

Thanks!

**Comment by ZeeRooo** [comment]
Thank you :+1: 

Added in v3.8.7: https://github.com/ZeeRooo/MaterialFBook/releases/tag/v3.8.7
