### ISSUE TITLE
Not Getting Notifications 

### ISSUE THREAD

**Issue by 3drinks** [ZeeRooo/MaterialFBook#198]
Not getting any of any kind. Have them all turned on. They worked just one day ago, and I'd really prefer to not use SMS....

**Comment by julio-b** [comment]
Android 6+ right? I think battery optimization is the problem here. Try to add an exception for MaterialFBook in Settings->Power manager->Battery optimization

**Comment by 3drinks** [comment]
Yes, I've done that and I still have to use another fdroid client to give me my notifications in material fbook. Which works I guess, but just a bit awkward.

**Comment by ZeeRooo** [comment]
It's fixed on 3.8.5
