### ISSUE TITLE
Could not install 3.8.5

### ISSUE THREAD

**Issue by rabelux** [ZeeRooo/MaterialFBook#201]
Just tried to update my 3.8.1 version to 3.8.5 but it it failed to install. Anyone else having this issue? 
Huawei p smart with Android 8.0.0

**Comment by rabelux** [comment]
Same for 3.8.6

**Comment by ZeeRooo** [comment]
Hmmm... I have tried it in Lollipop and Pie.

**Comment by rabelux** [comment]
Worked, thanks for your fast reply!
Now looking forward to check out what's new and it's great having you back :)
