### ISSUE TITLE
Push Notifications 

### ISSUE THREAD

**Issue by 3drinks** [ZeeRooo/MaterialFBook#205]
Enable push notifications. Prior I didn't get them, (and the app cannot enable them within) so i had a third party app relaying them. As of the 12/27 update, this workaround no longer works and I'm left with no push notifications at all.

**Comment by creativetrendsapps** [comment]
There is no push notifications for a Facebook wrapper. Go into MaterialFBook's settings and turn on notifications from there.

**Comment by 3drinks** [comment]
Even with notifications on, I do not get them.

**Comment by ZeeRooo** [comment]
Which android version do you have?

**Comment by 3drinks** [comment]
I'm on Nougat.

**Comment by ZeeRooo** [comment]
Make sure that you have the notifications allowed in _your phone's settings_

**Comment by 3drinks** [comment]
Yeah they're allowed.

**Comment by 3drinks** [comment]
FWIW, I had to unroot my device in order to use work related apps. As such, I'm back on Oreo. Push notifications are working...so this tells me it's an issue with Android Nougat (or lower) and your app. Hope this helps you.

**Comment by ZeeRooo** [comment]
I'm using Pie and it's working just fine.
I'll roll back to Lineage 14.1 to test the notifications, thank you.
Maybe it's a work library issue (it's a beta release after all)

**Comment by 3drinks** [comment]
That's possible. At least its working for me with current up to date firmware. Thanks for this app, I feel so much better about it than the spyware laced native app.

**Comment by ZeeRooo** [comment]
Is it working now?

**Comment by 3drinks** [comment]
Wow, this is a one year old necro, I had forgotten what this was even regarding.
