### ISSUE TITLE
Unable to silence notifications from threads

### ISSUE THREAD

**Issue by 3drinks** [ZeeRooo/MaterialFBook#208]
Expected behaviour: when I turn off notifications for certain threads in groups, i should not get notifications. 

Actual behaviour: notifications remain on, even though the drop down menu says notifications are off.

s8+, Oreo 8.0, December 2018 security patch

**Comment by creativetrendsapps** [comment]
You've also checked this same thing on the Facebook mobile site, right? If you did.. it's a bug on the mobile site... been like that for some time now.
