### ISSUE TITLE
Scrolling while making a long post on a small device

### ISSUE THREAD

**Issue by shoalcreek5** [ZeeRooo/MaterialFBook#217]
While trying to make a long post on a small device, MaterialFBook activates the refresh function without need, causing the entire post to be lost. It makes this app unusable for anything but browsing and short posts.

**Comment by creativetrendsapps** [comment]
> While trying to make a long post on a small device, MaterialFBook activates the refresh function without need, causing the entire post to be lost. It makes this app unusable for anything but browsing and short posts.

I'll submit a pull request

**Comment by austinhuang0131** [comment]
Scroll down first, then up; or move the text cursor up... For now.

**Comment by ZeeRooo** [comment]
What is a "small device"? I have no problems at all in my Moto E2 (4,5 inches, 480p) running Lineage 16

**Comment by shoalcreek5** [comment]
A small device would be anything small enough to use as a phone. 

So if you write a long post and while writing, scroll up to re-read what you had written, then scroll back down to continue writing, your app doesn't refresh the page and forget everything you wrote? Lucky you. On my stock Nougat, it refreshes and forgets every time, yet the newest version of Frost works great, even on long posts. They disable the "pull down to refresh the page" gesture when you are actively writing in a text field.

**Comment by ZeeRooo** [comment]
Please check the new release _v4.0.2_

**Comment by shoalcreek5** [comment]
Beautiful!
