### ISSUE TITLE
New versión 4.0

### ISSUE THREAD

**Issue by Temokk** [ZeeRooo/MaterialFBook#219]
No exit button. Can't download pics or videos as in version 3.87
Running android 10

**Comment by 65iDYff8r** [comment]
I also noticed that you can no longer copy text from a post, which was a pretty useful feature in the previous release. 
Thanks a lot for the awesome app!

**Comment by ZeeRooo** [comment]
I had removed the exit button because i think it's useless. You can close the app like everything else.
But regarding to the copy text feature, it was lost because of my theme rework, and i have completely forget about it. Will be re added asap.
