### ISSUE TITLE
top menu/search bar disappear

### ISSUE THREAD

**Issue by nakohlyth** [ZeeRooo/MaterialFBook#222]
the top menu/search bar get hidden after page is loaded even if the option to do so is unchecked/checked.
Android 9 (4.0 and 4.0.1)

**Comment by ZeeRooo** [comment]
Please check the latest version _v4.0.2_

**Comment by nakohlyth** [comment]
fixed with this version... although, I had to kill/restart app for the option to be effective... thankyou for the hard work
