### ISSUE TITLE
Sardinian is missing in the list of languages - version 4.0.1

### ISSUE THREAD

**Issue by asereze** [ZeeRooo/MaterialFBook#223]
Although the strings have been added via https://github.com/ZeeRooo/MaterialFBook/pull/216, Sardinian is still missing from the list of languages in the settings menu.

**Comment by ZeeRooo** [comment]
Please check the new release _v4.0.2_

**Comment by asereze** [comment]
@ZeeRooo Ok, it works now! Thank you very much!
