### ISSUE TITLE
[bug] Impossible to tag @Someone in comments 

### ISSUE THREAD

**Issue by nakohlyth** [ZeeRooo/MaterialFBook#225]
Hello,
it's impossible to tag @someone in comments, the "popup" doesn't show, just a blank frame, no more listing.
used to work, just noticed it doesn't anymore.
still working if I try write a post though.

**Comment by alex-dinh** [comment]
This might be an issue with facebook, not MaterialFBook. I can't tag via comments on the mobile site in chrome either. Need confirmation however.

**Comment by nakohlyth** [comment]
@alex-dinh  I only access Fbook from this app so didn't notice.checked and it seems indeed a facebook mobile issue then you're right. so I close it then, my bad
