### ISSUE TITLE
Bottom Navigation View Should Be Optional

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#23]
I don't like the new Bottom Navigation View and I wish I could disable it. It is redundant and takes up screen space. Please let us turn it off.

**Comment by ZeeRooo** [comment]
It was deleted in v2.4.5 https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.4.5.apk

**Comment by landry314** [comment]
cool, hasn't been pushed to f-droid yet though. i liked it better on the top. if you could choose top or bottom that works too.
