### ISSUE TITLE
"Messagges" is Spelled Wrong

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#24]
In "Notification settings", "Facebook messagges" should be spelled "Facebook messages". You have an extra "g".

**Comment by ZeeRooo** [comment]
Thanks for tell me the issue. It was fixed in v2,4,5: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.4.5.apk

I deleted the bottom navigation view too. See the changelog for more details about the update.
