### ISSUE TITLE
Disable Birthdays in the Events Feed As Well

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#25]
when disable birthdays is on it disables them in the news feed but not in the events feed. i would like to eliminate them in the events feed too if possible.

**Comment by ZeeRooo** [comment]
Im going to work on this. I will post here any news.

**Comment by ZeeRooo** [comment]
Yeah, i added it in the latest version (2.6.0)

**Download** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.6.0.apk
