### ISSUE TITLE
Missing Post button

### ISSUE THREAD

**Issue by miiichael** [ZeeRooo/MaterialFBook#29]
Attempting to share a ”On this day...” post. Discovered I can't, because there's no Post button! 

![screenshot_20161224-164647](https://cloud.githubusercontent.com/assets/4179353/21466182/a0e32892-c9fa-11e6-88a8-e7bddeeead8f.png)

For comparison, Tinfoil: 
![screenshot_20161224-165912](https://cloud.githubusercontent.com/assets/4179353/21466185/b1614bc2-c9fa-11e6-94ce-906f533f113a.png)

Device is stock Nexus 7, app version is 2.4.0 (latest available), according to F-Droid.

**Comment by ZeeRooo** [comment]
Try downloading the latest version from my repo. (Go to app and click "raw")

http://i.imgur.com/BTc8pHS.png

**Comment by miiichael** [comment]
2.4.5 showed up in F-Droid today. No luck I'm afraid (though I do really like the new location of the notification and message menus). 

![screenshot_20161226-142934](https://cloud.githubusercontent.com/assets/4179353/21476909/fb818158-cb77-11e6-9ed1-5c1e1cec571a.png)

**Comment by ZeeRooo** [comment]
Try downloading the apk from my repo, no fdroid

**Comment by miiichael** [comment]
My device doesn't want to install your .APK ("Can't open file"). Wrong mime type?

The current version in F-Droid still exhibits the bug.

**Comment by ZeeRooo** [comment]
1- I dont know what is the last version in fdroid, always is outdated, try downloading it from my repo (maybe your download is corrupted, try it again)
2- If the "cant open file" still, what is your android version?
3- I saw the blue top bar (with post and cancel button) dont appear when you are trying to share an event, i fixed it in the next version (2.8.0). What do you are trying to post?

**Comment by miiichael** [comment]
1. it wasn't outdated 6 days ago. As I generally check your repo way less frequently than every few days, F-Droid is a far more effective method of ensuring I have an up to date app.  :stuck_out_tongue: 
I really don't think it's a corrupted file problem. It wanted to open the APK in Moon+ Reader (and a different ereader app forgotten). After uninstalling both apps, I was hoping for something other than "Can't open file". I'm pretty sure the problem is that the file is being returned from github as text/html (rather than [application/vnd.android.package-archive](http://stackoverflow.com/questions/7489605/web-host-issue-apk-files-to-download-from-android-browser)), thus convincing my tablet to attempt to open them in ereader apps instead of the Android package manager.

2. Device is a second gen Nexus 7, running Android 6.0.1.

3. I'm not sharing an event. As per the original bug description, I'm sharing an ”[On this Day](https://www.facebook.com/onthisday/)...” post.

**Comment by ZeeRooo** [comment]
You can have the app update according to fdroid, but most of the times
fdroid have the app uotdated according to my repo. The best way to have the
app FULLY UPDATED is downloading it from my repo, its signed too. Why
fdroid is outdated? See #18
Anyway, in going to check "on this day" :)

**Comment by miiichael** [comment]
At the risk of straying off topic...

If I (eventually successfully) install from github, will the app be automatically kept up to date? Manually checking for updates is obviously not a scalable way of staying up to date.

I'm not going to pretend I understand the issues mentioned in #18 (or any of the other specifics of building Java applications :sweat_smile:), but it does sound a tiny bit like you keep requiring (versions of) tools that do not exist on the build server. Or looking at Build-Tools, you seem to want [25.0.2](/ZeeRooo/MaterialFBook/blob/master/.travis.yml), but the Android [documentation](https://developer.android.com/studio/releases/build-tools.html) only goes up to 25.0.1. Does your software really fail to build with 25.0.1? :stuck_out_tongue: (Somewhat more seriously, I'm guessing it's a case of there being no way to express "I need 25.0.0 _or newer_", and that it's probably the build server's fault for not keeping up.)

**Comment by ZeeRooo** [comment]
Yes thats the problem.
Check updated manually is the only way to get the app up to date if the
build server of fdroid have the build tools updated, i dont know what
version they have right now, but they need a few days (or weeks) to update
the build tools before google release it. I always put up-to-day libraries
into my app (you know, security, stability, functions, fixes, and probably
better performance)
