### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by Kravcian** [ZeeRooo/MaterialFBook#30]
Hello everyone.
Thanks for the app ! Really useful.

Nevertheless I noticed that the app drains a lot of my battery. I downloaded the last version from F-Droid on my Nexus 5 (running on Marshmallow OS). My phone says that the app uses 23% of the battery. I find it weird because I don't use the app more than one hour per day.

Does anyone else notice that? 

Thanks for reading.

**Comment by alekksander** [comment]
Do You use notifications?

**Comment by Kravcian** [comment]
Hi, thanks for answering.

Nope, I wasn't using notifications.

**Comment by ZeeRooo** [comment]
Close the app when dont use it. This app use the internet to refresh the notifications and the badge _(the number on the icons on the toolbar)_

**Comment by ZeeRooo** [comment]
@Kravcian Please try the 2.7.0. I think the battery will be more healthy with the latest changes,
https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.7.0.apk
