### ISSUE TITLE
Chat view & external link desynchronization with the feed

### ISSUE THREAD

**Issue by jcsantosx** [ZeeRooo/MaterialFBook#31]
Hello.
Not really 2 bugs, but 2 suggestions and also not shure if should suggest here or to 'Toffeed' project, but you decide what to do with this.

Chat view:
The facebook itself, have a small text field where we can write, plus in mobile the keyboard consume at least 50% of the screen area, and if we trying to check if we wrote/spell right the message(cause we can't see the text) the menu shows up at the bottom.
If you can find a way to fix the text field for the message at the top of the screen(#top or getElementById...), would be fantastic (or disable/move location the menu that appears at the bottom.

External link desynchronization with the news feed:
When we click in a link(youtube, website, gif..) in the feed, launch the favorite browser that opens that link, but when we came back to MaterialFBook, we have to restart the scroll until we find that previous location where we clicked(to see the remaining feed until the end).
If you can find a way to markdown/href the location(#current_message or getElementById...) that would be nice as well.

The rest is perfect ;)

**Comment by ZeeRooo** [comment]
Those issues were fixed in **v2.5.0**

You can **download** it from here: https://raw.githubusercontent.com/ZeeRooo/MaterialFBook/master/apks/MaterialFBook_2.5.0.apk
