### ISSUE TITLE
"Save Data" Setting Forces Basic Site

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#33]
Save Data (when enabled, the app autoconfigure to save data) seems to simply turn on the facebook basic mode in MaterialFbook 2.4.5... From this description I don't see why this is the action. Is this a bug or is this setting description miswritten? Is this the basic mode switch?

**Comment by kowith337** [comment]
Are you using under cellular data?
If yes, I have a same issue here... #28

**Comment by ZeeRooo** [comment]
I dont know why. I tried with 4G and 2G _(Carrier: Claro, in Argentina)_ and it worked fine.

**Comment by kowith337** [comment]
For me, I'm still get the mobile/touch version on cellular data, plus a page cover to promote and suggest to use Facebook on "Free Basics" when I'm open web/app, I guess it's depend on what mobile carrier are collaborate with Facebook to offer that service.
_Currently know have dtac and TrueMove-H in my country (Thailand)_

**Comment by ZeeRooo** [comment]
mbasic.facebook.com work on your browser?

**Comment by kowith337** [comment]
@ZeeRooo Get redirected to `http://h.facebook.com/hr/r?...` and sent back to `m.facebook.com` or `mobile.facebook.com`
Remark, redirect to `h.facebook.com` is done with non-HTTPS.

**Comment by ZeeRooo** [comment]
In my case, when i go to h.facebook.com, it redirect to m.facebook.com (i
tried with and without http)

**Comment by alekksander** [comment]
perhaps my input can help somehow. when browsing on my phone, (cellular operator: orange (PL)):

mbasic.facebook.com > stays on mbasic.f…
m.facebook.com         > stays on m.f…
h.facebook.com          > goes to m.f…

MaterialFBook when using „save data” is showing mbasic.facebook.com. i understand that this is desired behavior?

**Comment by ZeeRooo** [comment]
Yes, that is the idea. When you enable "save data" the app load into the
mbasic, and dont update user info (number of notifications and messages in
the toolbar, no profile pic and cover)

**Comment by kowith337** [comment]
I don't know is it helpful here? because I've tested last year.
Tested by open `https://mbasic.facebook.com/home.php?sk=h_chr` without logging in to trigger Facebook redirect to login page.
Done with Firefox for Android and use uBlock Origin to block ads and observe network requests.

This is when using local/home Wi-Fi network.
- This doesn't redirected to other sub-domain.
![image](https://cloud.githubusercontent.com/assets/16535467/22201487/67616256-e196-11e6-8ac0-4786745d4597.png)

And this is when using on cellular data.
- It's first redirect to `mobile.facebook.com`
- then redirect to `h.facebook.com` **without HTTPS** at this process.
- and redirect to `mobile.facebook.com` twice, then sent to login page, but last destination is `m.facebook.com`
![image](https://cloud.githubusercontent.com/assets/16535467/22201520/8d6ce7a4-e196-11e6-850b-6ae305d477a2.png)

**Comment by landry314** [comment]
so why is it called "Save Data"? This name for the setting is completely unclear. What data is saved? Why not call the setting "Use basic mode"?

**Comment by ZeeRooo** [comment]
Because the basic mode use less data than the mobile.facebook.com. also
this mode disable the badge and profile info sync

**Comment by alekksander** [comment]
i have to agree with landry314, it should be called „use basic mode” and has saving data info in description, like „when enabled, it uses basic interface and doesn't auto—refresh” or something.

**Comment by ZeeRooo** [comment]
Is the same... If i rename it we need to traslate it again..

**Comment by landry314** [comment]
Sorry but "save data" is completely unclear and a VERY bad name for it. it sounds like it is some kind of logging or backup system... the basic mode uses less downloaded data, i understand, but that doesnt mean you should name the setting after one thing it does: the basic mode is an entirely different interface.

I suggest "Use Basic Mode" or if you want to make the data issue clearer then "Use basic mode to reduce data consumption". If you don't like that then maybe "Lower Data Mode", "Less Bandwidth Mode", or just "Basic Interface" or "Low-data interface". Since you like the word "save" and "data", "Save Internet Data" could be used to at least make it clear what data you are referring to but it is still not that clear. "Reduce Internet Data Consumption" is good too but it doesn't explain HOW it is doing that which is why I suggested "Use basic mode to reduce data consumption". This makes it clear you are changing the facebook interface to reduce the data that is being pulled down.

**Comment by ZeeRooo** [comment]
@landry314  @alekksander 
I changed the name in **v.2.5.0** https://github.com/ZeeRooo/MaterialFBook/blob/master/app/src/main/res/values/strings.xml#L78

**Download** the new version from here: (yes, the random sites after go back from external sites was fixed) https://raw.githubusercontent.com/ZeeRooo/MaterialFBook/master/apks/MaterialFBook_2.5.0.apk
