### ISSUE TITLE
Android notification bar overlapping app

### ISSUE THREAD

**Issue by IKRadulov** [ZeeRooo/MaterialFBook#34]
I am using pure android 4.4.2 on evolio S4 cobalt device and the app is overlapped by the android notification bar .

**Comment by ZeeRooo** [comment]
Can you post a screenshot of the issue?

**Comment by IKRadulov** [comment]
Here it is
![screenshot_2017-01-08-18-37-22](https://cloud.githubusercontent.com/assets/21968311/21751604/8ac3b480-d5d2-11e6-84ef-6e375260f6cf.png)

**Comment by ZeeRooo** [comment]
This issue appear in the last update? Please chek in older versions

**Comment by IKRadulov** [comment]
This appears on any Version >= 2.4.0 (From Fdroid)

**Comment by ZeeRooo** [comment]
@IKRadulov  It was fixed in v2.5.0.
**Download** it from here: https://raw.githubusercontent.com/ZeeRooo/MaterialFBook/master/apks/MaterialFBook_2.5.0.apk

Enjoy and tell me :)

**Comment by IKRadulov** [comment]
Everything now works fine mate ! 
Will you push updates on fdroid ?

**Comment by ZeeRooo** [comment]
Im not a member of fdroid, sorry.
