### ISSUE TITLE
Maki

### ISSUE THREAD

**Issue by creativetrendsapps** [ZeeRooo/MaterialFBook#35]
The app that replaces this app needs to be opened sourced as well as you need to follow the license of Folio for Facebook as well as FaceSlim and SlimSocial which are all under GPLv3. This needs to be corrected as soon as possible.

**Comment by ZeeRooo** [comment]
Done https://github.com/ZeeRooo/MaterialFBook/commit/2cbd33686513dd9060b436a40afac779776eed3a

**Comment by ZeeRooo** [comment]
I have curiosity to know what happened with Folio, @creativetrendsapps 
Sorry for the question.

**Comment by creativetrendsapps** [comment]
@ZeeRooo , it was sold to Friendly IO. It remains open source though.

**Comment by ZeeRooo** [comment]
Ohh, nice. Maybe they are going to make a fusion betwen folio and their own fb client

**Comment by creativetrendsapps** [comment]
@ZeeRooo , that is the goal.

**Comment by ZeeRooo** [comment]
It look really nice. Your app is really good, the best thing to do is optimize the notification service for less ram consumption. Im very noob to do this.

**Comment by creativetrendsapps** [comment]
@ZeeRooo Folio doesn't use much background ram though, it's using ram if the app is left open.

**Comment by ZeeRooo** [comment]
Noob question coming: is very hard to get the profile picture from the user
to put this image into the notification, you know, profile image into the
notification instead of a custom png.
I saw it in Friendly and Swipe.
I want to have this feature but i dont know how to start.
