### ISSUE TITLE
Page offset in wrong direction when keyboard is open

### ISSUE THREAD

**Issue by gchameleon** [ZeeRooo/MaterialFBook#36]
On Android 4.4, the page offsets in the wrong direction when the keyboard is opened.

**Comment by ZeeRooo** [comment]
Sorry, can you explain more about the issue? I dont understand well.

**Comment by gchameleon** [comment]
This is what it looks like:
![screenshot_2017-02-04-14-16-52](https://cloud.githubusercontent.com/assets/15675418/22622701/5d844626-eb42-11e6-89a3-62da603b46fe.jpeg)
Instead of shifting up to show the input field, the page shifts down by the same amount.

**Comment by ZeeRooo** [comment]
Ok, im working on it.

**Comment by gchameleon** [comment]
Thanks

**Comment by ZeeRooo** [comment]
i think its fixed in 2.6.0. 
**Download** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.6.0.apk

Please tell me if its working.
