### ISSUE TITLE
Search doesn't Work anymore

### ISSUE THREAD

**Issue by dklueh79** [ZeeRooo/MaterialFBook#37]
In 2.5.1 the Search on the left menue doesn't work anymore.it is shown the body, but nothing happens during search

**Comment by ZeeRooo** [comment]
Yes, i know. I fixed it in the 2.6.0. In a few hours im going to upload this new version (maybe tomorrow).
Sorry for the inconvenient.

**Comment by ZeeRooo** [comment]
Its fixed in 2.6.0. 
**Download** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.6.0.apk
