### ISSUE TITLE
menu bar color doesn't change with material look of the app

### ISSUE THREAD

**Issue by kojak1989** [ZeeRooo/MaterialFBook#39]

**Comment by ZeeRooo** [comment]
Can you post a screenshot of the issue?

**Comment by kojak1989** [comment]
Here you go, and can you add this string to translation from GitHub what I
post?

10.02.2017 7:54 PM "Juan" <notifications@github.com> napisał(a):

> Can you post a screenshot of the issue?
>

**Comment by kojak1989** [comment]
Btw, can you look at in-built messenger? Because I have issues with sending
images and videos.

10.02.2017 8:03 PM "Koji K" <kadzielakamil@gmail.com> napisał(a):

Here you go, and can you add this string to translation from GitHub what I
post?

10.02.2017 7:54 PM "Juan" <notifications@github.com> napisał(a):

> Can you post a screenshot of the issue?
>

**Comment by kojak1989** [comment]
Still not translated.

10.02.2017 8:54 PM napisał(a):

Btw, can you look at in-built messenger? Because I have issues with sending
images and videos.

10.02.2017 8:03 PM "Koji K" <kadzielakamil@gmail.com> napisał(a):

Here you go, and can you add this string to translation from GitHub what I
post?

10.02.2017 7:54 PM "Juan" <notifications@github.com> napisał(a):

> Can you post a screenshot of the issue?
>

**Comment by ZeeRooo** [comment]
Where is the issue?

**Comment by kojak1989** [comment]
Sorry I don't play with GitHub very much and it's not issue just not
translated string ☺️

11.02.2017 10:32 PM "Juan" <notifications@github.com> napisał(a):

**Comment by ZeeRooo** [comment]
No problem, but can you explain more about the inconvenient? or post a screenshot?

**Comment by kojak1989** [comment]
I already send to you screenshot with not translated words in my language :)

2017-02-11 22:39 GMT+01:00 Juan <notifications@github.com>:
