### ISSUE TITLE
Trying to be nice here

### ISSUE THREAD

**Issue by creativetrendsapps** [ZeeRooo/MaterialFBook#4]
You're using code from Folio and are NOT giving credit to the original source as is needed. You've also removed the copyright notice that should remain in place in some of the classes in which you borrowed code. You've taken Folio's entire Navigation Drawer removal code and haven't given any credit to the source. At the very top of this source code: https://github.com/creativetrendsapps/FolioforFacebook/blob/master/app/src/main/java/com/creativtrendz/folio/fragments/Navigation.java there's a copy right notice that needs to be followed. This needs to be fixed as soon as possible.

**Comment by XxXSnipper** [comment]
Sorry sir. I fixed this, chek the commits.
