### ISSUE TITLE
Why is platform support needed?

### ISSUE THREAD

**Issue by troopermax** [ZeeRooo/MaterialFBook#41]
I like to have Facebook's platform/app support disabled, but this app requests it - why is it needed? If it is needed for certain things, then maybe just those certain things could be disabled without it? I'm coming from Tinfoil for Facebook and it could do most things and never asked for platform support. This app does feel refreshing though and looks like it can handle messaging better.

**Comment by hackel** [comment]
It pulls in your name, profile photo, and cover photo to display in the navigation drawer.  Certainly not essential!

**Comment by ZeeRooo** [comment]
@troopermax Try the B-3.5.0, i removed the FB Sdk. Anyway we used this api to get profile name, picture, cover and upload photos/videos to your wall.
