### ISSUE TITLE
Issues with sending pictures and videos with in-built messenger

### ISSUE THREAD

**Issue by kojak1989** [ZeeRooo/MaterialFBook#42]

**Comment by ZeeRooo** [comment]
Explain more. I cand send pictures in chats

**Comment by kojak1989** [comment]
i add this in github to requests and one more issue.

2017-02-12 12:39 GMT+01:00 Juan <notifications@github.com>:

**Comment by kojak1989** [comment]
when i trying to send something i allways have triangle with "!"

**Comment by kojak1989** [comment]
instead of loading bar i allways have this triangle

**Comment by ZeeRooo** [comment]
Android version

**Comment by kojak1989** [comment]
6.0.1 Xiaomi Redmi Note 3 Pro International but on my other device nexus 5x with 7.1.1 is ok.

**Comment by ZeeRooo** [comment]
You can upload photos with the browser in m.facebook.com in the Redmi?

**Comment by kojak1989** [comment]
it forced messenger for use.

**Comment by kojak1989** [comment]
messenger app.

**Comment by ZeeRooo** [comment]
I cant do anything. Is a facebook page issue.

**Comment by kojak1989** [comment]
ok,thanks.
