### ISSUE TITLE
[Feature Request / Experimental] Force lower data mode

### ISSUE THREAD

**Issue by kowith337** [ZeeRooo/MaterialFBook#44]
**Idea**

To force Facebook allow user to access basic mode on mobile data if some cellphone provider have "Free Basics" service available.

**The Problem**

Some mobile network carrier had collaborate with Facebook to allow and offer "Free basics" service to let users use Facebook and browse some website that participate with "Free basics" without data charges.
But this service also disable some function of Facebook, like accessing [basic site](https://mbasic.facebook.com), certain function of another app (e.g. Pages manager) also unable to use because of subdomain redirection.

**Reproduce Issue Details**

1. Switch to mobile network.
2. Enable "Save data / Lower data" mode.
3. Go back to main page.

If you've got mobile/touch page or a page that tell you to use "Free basics", this confirmed cellphone provider that you're using is have "Free basics" service and lockdown you to prevent accessing basic site directly, unless using some trick to bypass.

**How it works?**

1. Enable "Force lower data mode" will be disable JavaScript in this wrapper browser.
2. In the main page of mobile/touch version, Facebook will be giving up to show news feed and will be show "Switch to basic version" link at news feed area.
3. When user click "Switch to basic version", the basic version of Facebook will be loaded.

**Conflicts**

- May not work at all, and also completely break! (the basic version link may not appear) consider to test first.
- Notifications will be broken becaus JavaScript was disabled, and forcing to use basic version of Facebook will be also apply in [normal mode](https://m.facebook.com), where the notifications will be fetch.
- Messenger support also completely not work (yes, cause of disable JS), consider to use Messages/Chat inside basic version of Facebook instead.

**Notes**

- Facebook and/or cellphone provider will be redirect you if you trying to access [basic site](https://mbasic.facebook.com) to
> - non-HTTPS redirecttion on `h.facebook.com/hr/r?...`
> - `mobile.facebook.com` is the last destination that it sent you to...

- Doing this so it's still trapped you into `mobile.facebook.com` but the layout will refer to your choice (or you've enforced to use basic version)
- Benefits of disable JavaScript is also prevent hidden tracking frame (`xti.php`) if sponsored posts appear in news feed of basic version.
- You can change your mind to switch back to mobile/touch version by clicking "Switch to regular view" that highlighted with light yellow background at the top of page.

**Comment by ZeeRooo** [comment]
But the "free facebook" in some carriers is "https://0.facebook.com", or im
wrong?
(In my country and carrier, this service is unavaible)

**Comment by kowith337** [comment]
Yes, you can access Facebook under "Free basics" by that url.
But I'm not use. (and never to...)

The "Save Data / Lower data" was messed by Facebook itself and/or operator by subdomain redirect, I'm still want to use basic version on mobile data, this is the main goal.
- "Basic site" isn't same as "Free basics" because basic site can view images and videos.
- But "Free basics" was hide images and videos, and show the placeholder that tell "use data to view" instead.)

**Comment by ZeeRooo** [comment]
Ohh, the free basic is very limited.
You want a feature who automaticaly switch to basic mode when you are in
mobile data? (3g, 2g. Etc)?
If yes, the answer is simple, other users  want the mobile version in wifi
or data instead the basic because in the mobile we have photo cover, photo
profile, notifications and is more beutifull than the basic. I think the
best way to do it is let to the user decide when he want the basic version
or the mobile.
But, a good future feature is add an option to use the free basic, maybe
some users have it abaile with his carrier and country (for only send
messages or similar)

**Comment by kowith337** [comment]
Even in the normal mode (touch layout), it's have connections to ´mobile.facebook.com´ to fetch feed/messages/notifications instead of staying every connections at same domain (´m.facebook.com´ or ´touch.facebook.com´), that's how the basic mode was unable to access when use cell data because everything was redirected and point to ´mobile.facebook.com´.
And I don't have any issues when I'm using home or public Wi-Fi because it doesn't have forcible redirection like that!

In my opinion, I don't want to use that service, never...
But it's your choice to support that, I don't care.
