### ISSUE TITLE
Can not invite friends to events

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#45]
looking at an event and tapping "share" then "invite friends" does nothing... just nothing... i cant invite friends to any event using this app.

**Comment by ZeeRooo** [comment]
You can do it with m.facebook.com in the browser (chrome for example)

**Comment by ZeeRooo** [comment]
Sorry, it was a question, i forget the **"?"** @landry314 
Im looking right now in the browser, but when i tap in "invite friends" does nothing. It is a problem with facebook page, no my app.

**Comment by ZeeRooo** [comment]
It was fixed on **v2.8.0:**.

You can **download** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.8.0.apk?raw=true
