### ISSUE TITLE
please put back hide newsfeed function

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#46]
why did you remove the hide newsfeed option? i dont want to see the newsfeed. that was a great option.

**Comment by ZeeRooo** [comment]
Ohh sorry, in the next version i'll add the option

**Comment by ZeeRooo** [comment]
I re-added the option to hide all the news feed in the **2.7.5**

You can **dowmload** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.7.5.apk?raw=true
