### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by ThePx** [ZeeRooo/MaterialFBook#49]
When I open a notification it leads me to the news feed instead of to the source of the notification.

**Comment by ZeeRooo** [comment]
Yes, i saw it recently.
Dont worry, it will be fixed in the next version

**Comment by ZeeRooo** [comment]
It was fixed on **v2.8.0**.

You can **download** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.8.0.apk?raw=true

**Comment by bolo79** [comment]
Issue is back in 2.9.0
