### ISSUE TITLE
Navigation Menu Items Should Say "Show" Not "Hide"

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#51]
In the Navigation Menu Items in Settings you have a list of what to put on the left slide drawer. in the ON position you SHOW the items, in the OFF position you HIDE the items so shouldn't logically the description say "Show 'Groups' button on navigation drawer." and "Show" for all of them really. It feels backwards this way. The ON position should be doing what the description says which is SHOWING the button.

**Comment by ZeeRooo** [comment]
lol
You are right. My english sucks

**Comment by ZeeRooo** [comment]
It was corrected in the **v2.8.0**

You can **download** it from here:  https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.8.0.apk?raw=true
