### ISSUE TITLE
Rename "Messages only" and Expand Its Function

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#52]
The new feature "Messages only" is great because I totally use this app mainly for messages but the name is not clear. It should be "Start in messages" or "Make Messages the default page" or something like that. The word "only" means excluding everything else but we are not excluding other functions of the app we are only beginning with a certain one.

I suggest also expanding this feature to allow us to choose many places to start the app in. Maybe create a pulldown menu that has the following options "Newsfeed, Messages, Events, Main Menu, Groups, Photos, Friend Requests, None" and whatever else you think people might want to load at startup. Having the option "None" might be just like you used to have where the newsfeed is hidden, blank page at startup. Maybe call the option "Start app with this page" or something like that. I think this would be very useful for many people who never use the newsfeed but use other functions of facebook a lot.

**Comment by ZeeRooo** [comment]
Thanks for the request and report.
I corrected the line in the **v2.8.5**

You can **download** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.8.5.apk?raw=true

**Comment by ZeeRooo** [comment]
This feature was implemented in **v3.1**

Plase **download** it and try :) https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.1.0.apk
