### ISSUE TITLE
Menu bar colour doesn't change with material app colour

### ISSUE THREAD

**Issue by kojak1989** [ZeeRooo/MaterialFBook#54]
![screenshot_20170303-090410](https://cloud.githubusercontent.com/assets/25568358/23543065/b3edb282-fff0-11e6-9c6b-5b6ac37cc591.png)

**Comment by ZeeRooo** [comment]
The blue bar never change, its hiden 90% of the times, its displayed if you
show it in settings or if you are in share page.

El viernes, 3 de marzo de 2017, kojak1989 <notifications@github.com>
escribió:
> <
https://ci4.googleusercontent.com/proxy/gNWPodiww6UUN6Fv6tn_sOWdy5CRB_BH2BHGHmDNEYmr54mWsPINzggWf9ZyRxCZoAabPqiVdP9epOfH7C0jmjGjvTElltUnj5wi2ikpU-BXsU7n-1fNhbYz1yl-BeFJfxsS4NhoALaHt5QEysuIIrOzaJVy8MO7Bdut=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/25568358/23543065/b3edb282-fff0-11e6-9c6b-5b6ac37cc591.png
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/ME2dTbvfuNGzQHNJ3wQYUHjLyk2A9SNY8fWqDa5cvOUzU1PF9Cz9ZuGEN4ZBCKxnwZuU_C1dfFSshkNWYlDJDkexMhMbFpOvAIHFnGJF_TuQb1Rb3TfgVVGcSfW1fK6-cVy4L3QKB--a55_tD_B1fqdPggUzNA=s0-d-e1-ft#https://github.com/notifications/beacon/ASmIAE60IOQRbyCmWtJSSppd4aSdbDFCks5rh8pkgaJpZM4MR-Nc.gif>

**Comment by kojak1989** [comment]
better would it look like changing color with the application don't you think ?

**Comment by ZeeRooo** [comment]
Please take a look at the version 3.0  with **new web themes**.

You can **download** it from **here:** https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.0.0.apk

**Comment by kojak1989** [comment]
ok, thanks for info !

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-03-18 8:13 GMT+01:00 Juan <notifications@github.com>:

**Comment by kojak1989** [comment]
Still the same with latest version

**Comment by ZeeRooo** [comment]
Choose the theme in "Web Themes"

2017-03-18 17:19 GMT-03:00 kojak1989 <notifications@github.com>:

**Comment by kojak1989** [comment]
where is this option ? Because when i do this from left side menu of the app, color is changing but not right away, can you fix it?

**Comment by ZeeRooo** [comment]
In settings above of app themes.......

**Comment by kojak1989** [comment]
yes color is changing but not right away.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-03-19 14:21 GMT+01:00 Juan <notifications@github.com>:

> In settings above of app themes.......
>

**Comment by ZeeRooo** [comment]
So, i dont know what do you want

**Comment by kojak1989** [comment]
t too much concerned about details, do not worry about it :D

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-03-19 15:31 GMT+01:00 Juan <notifications@github.com>:

> So, i dont know what do you want
>
