### ISSUE TITLE
Can't share images with long tap

### ISSUE THREAD

**Issue by yarons** [ZeeRooo/MaterialFBook#55]
I tried sharing an image directly from the app, I entered the image itself, clicked view full and then long tapped the high quality image and tried sharing it, the app crashed, I tried several times, same result. 

I'm running Android 7.1.1 (cm 14.1) on OnePlus One.

**Comment by ZeeRooo** [comment]
Try with the 2.9.0

**Comment by yarons** [comment]
I'm not sure this is the desired action since now I can't long tap the image at all thus can't share it at all.

**Comment by ZeeRooo** [comment]
Now to share an image we need to open the photo viewer (view full size, and
the share icon in the toolbar)

**Comment by yarons** [comment]
It's this a planned feature?

**Comment by ZeeRooo** [comment]
Of course
