### ISSUE TITLE
Page updates when I try to scroll through the text field

### ISSUE THREAD

**Issue by darksidecorrales** [ZeeRooo/MaterialFBook#56]
When I trying to move around the tiny text field when adding a post to a group... the page refreshes and deleting the information entered.
Is possible to disable refresh by scroll temporally until finish to edit it?
Thank you.

**Comment by alekksander** [comment]
i've also became a victim of this, and one person whom i recommended this application to also complained about it. i think it was reported (by me) some time ago, as „refresh is too easily triggered” or something, and there was not too much to do about it.

**Comment by ZeeRooo** [comment]
Fixed in v3.4.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk

**Comment by alekksander** [comment]
not entirely. would it be possible to disable swipe refresh if text is entered in text field when messaging?

**Comment by alekksander** [comment]
or simply an option do disable swipe refresh in messages by selecting proper switch in menu (auto disable if text entered is better if possible)

**Comment by alekksander** [comment]
Bump

_Sent from my Cat S40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
