### ISSUE TITLE
Can't share article via share button

### ISSUE THREAD

**Issue by darksidecorrales** [ZeeRooo/MaterialFBook#57]
When I click on a link on a web page to share something by Facebook and the application opens it does not load this link to share it but opens my wall, making it impossible to share the article using this method.

**Comment by ZeeRooo** [comment]
Can you explain more? You are trying to share a web page from the browser
to MFB or a simple facebook post to your wall?

**Comment by darksidecorrales** [comment]
I try to share an article in a webpage via Facebook share button in this website, but the app goes to timeline, it should go to new post page with a link to this article. If I share via Facebook in browser it opens correctly.
Thank you.

**Comment by ZeeRooo** [comment]
Its working on Lollipop 5.1, what is your android version?

**Comment by darksidecorrales** [comment]
I have android 7.1.1

**Comment by ZeeRooo** [comment]
I tried it in AVD 7.1 and worked fine, please try with the v3.0 and tell me if the issue continue.

You can **download** it from **here:** https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.0.0.apk

**Note:** Now, to share a page, for example; facebook post, you need to open the post, click in the fab and select the "share" button, later the app automatically write a status with the url of the post.

**Comment by darksidecorrales** [comment]
Hi. I have trying with 3.0 version and nothing changes... Watch this screen record: https://youtu.be/L1DSzDEz8wo
Thanks for your time.

En 18 de marzo de 2017 8:17:29 Juan <notifications@github.com> escribió:

I tried it in AVD 7.1 and worked fine, please try with the v3.0 and tell me if the issue continue.

You can download it from here: https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.0.0.apk

Note: Now, to share a page, for example; facebook post, you need to open the post, click in the fab and select the "share" button, later the app automatically write a status with the url of the post.

**Comment by darksidecorrales** [comment]
Your name is Juan? Are you Spanish?

En 18 de marzo de 2017 8:17:29 Juan <notifications@github.com> escribió:

I tried it in AVD 7.1 and worked fine, please try with the v3.0 and tell me if the issue continue.

You can download it from here: https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.0.0.apk

Note: Now, to share a page, for example; facebook post, you need to open the post, click in the fab and select the "share" button, later the app automatically write a status with the url of the post.

**Comment by ZeeRooo** [comment]
Ohhh, thank you so much for the video! I can see very good the issue, im
going to work on it

**Comment by darksidecorrales** [comment]
Thank you very much!

En 18 de marzo de 2017 16:47:29 Juan <notifications@github.com> escribió:

Ohhh, thank you so much for the video! I can see very good the issue, im
going to work on it

**Comment by darksidecorrales** [comment]
I also wonder if some way to keep the application active is possible, because after a while it stops sending notifications. I've already tried removing the Android optimization in this application, but it's still stopping.
Perhaps with an notification in the bar who keeps the app active.
Thank you!

En 18 de marzo de 2017 16:47:29 Juan <notifications@github.com> escribió:

Ohhh, thank you so much for the video! I can see very good the issue, im
going to work on it

**Comment by ZeeRooo** [comment]
The app still running in background (if you have notifications enabled), we are using AlarmManager to schedule the notifications sync task, since KitKat, Google did this system a little inexact to prevent battery drains, for example: if you set the notifications sync tine in 5min, if the app is in background it can be 6min aprox (or less, its managed by Android OS). So, if the device is in deep sleep (doze activated in Marshmallow+) the Android OS disable or make it 7/8min instead of 5min (all to prevent battery drains). If you are using the app or the device in general, the notification sync time is exact (5min for the example).
Pst: Yes, mi name is Juan, i speak spanish, my english is not good enough but i do my best :)

**Comment by darksidecorrales** [comment]
I'm Spanish too! 😃
I understand that I can only speak English in here. What I said is that in my case the application stops notifying in time, as if Android stopped. I get two or three notifications and no more.

En 18 de marzo de 2017 18:43:33 Juan <notifications@github.com> escribió:

The app still running in background (if you have notifications enabled), we are using AlarmManager to schedule the notifications sync task, since KitKat, Google did this system a little inexact to prevent battery drains, for example: if you set the notifications sync tine in 5min, if the app is in background it can be 6min aprox (or less, its managed by Android OS). So, if the device is in deep sleep (doze activated in Marshmallow+) the Android OS disable or make it 7/8min instead of 5min (all to prevent battery drains). If you are using the app or the device in general, the notification sync time is exact (5min for the example).
Pst: Yes, mi name is Juan, i speak spanish, my english is not good enough but i do my best :)

**Comment by darksidecorrales** [comment]
Hi!
When I try to open a Google search link to Facebook in the app isn't work too.
Look: https://youtu.be/IPa57q7OpVQ

En 18 de marzo de 2017 18:43:33 Juan <notifications@github.com> escribió:

The app still running in background (if you have notifications enabled), we are using AlarmManager to schedule the notifications sync task, since KitKat, Google did this system a little inexact to prevent battery drains, for example: if you set the notifications sync tine in 5min, if the app is in background it can be 6min aprox (or less, its managed by Android OS). So, if the device is in deep sleep (doze activated in Marshmallow+) the Android OS disable or make it 7/8min instead of 5min (all to prevent battery drains). If you are using the app or the device in general, the notification sync time is exact (5min for the example).
Pst: Yes, mi name is Juan, i speak spanish, my english is not good enough but i do my best :)

**Comment by ZeeRooo** [comment]
Im working to fix the share issue, it only happen in 7.1. (i tried in 7.0
and worked for me).
Another bug to fix 😵

2017-03-19 17:25 GMT-03:00 darksidecorrales <notifications@github.com>:

> Hi!
> When I try to open a Google search link to Facebook in the app isn't work
> too.
> Look: https://youtu.be/IPa57q7OpVQ
>

**Comment by darksidecorrales** [comment]
Don't worry! Pass by pass 😉
I only communicate the bugs I see. It's not a critic, of course. I really appreciate your work and if I could I would help you with it.
Thank you!

En 19 de marzo de 2017 21:49:16 Juan <notifications@github.com> escribió:

Im working to fix the share issue, it only happen in 7.1. (i tried in 7.0
and worked for me).
Another bug to fix 😵

2017-03-19 17:25 GMT-03:00 darksidecorrales <notifications@github.com>:

> Hi!
> When I try to open a Google search link to Facebook in the app isn't work
> too.
> Look: https://youtu.be/IPa57q7OpVQ
>

**Comment by ZeeRooo** [comment]
Ok, according to AVD 7.1.1, i fixed both issues. 
Please try it and tell me :) https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.1.0.apk

**Comment by darksidecorrales** [comment]
https://youtu.be/LeZA7IsbtF8
👏👏👏👏

En 21 de marzo de 2017 2:14:18 Juan <notifications@github.com> escribió:

Ok, according to AVD 7.1.1, i fixed both issues.
Please try it and tell me :) https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.1.0.apk

**Comment by ZeeRooo** [comment]
😁😁😁😁
Enjoy it :)

**Comment by darksidecorrales** [comment]
Thank you!
I have a loot of ideas, but I don't want to disturb you 😉
Thanks for your patience.

En 21 de marzo de 2017 10:24:20 Juan <notifications@github.com> escribió:

😁😁😁😁
Enjoy it :)

**Comment by ZeeRooo** [comment]
Hahaha no problem, tell me. Maybe i can implement it in next releases.

**Comment by darksidecorrales** [comment]
For example:
Possibility to add more social networks (Twitter, Instagram, G+...) using add-ons with the purpose to not make the app heavier than you need. Each add-on would be a social network to add to the main application ... I do not know if I'm saying a blunder or it's possible to do this ...
A greeting.

En 21 de marzo de 2017 10:36:16 Juan <notifications@github.com> escribió:

Hahaha no problem, tell me. Maybe i can implement it in next releases.
