### ISSUE TITLE
Crash (stopped working) when tapping E-mail button on Page contact

### ISSUE THREAD

**Issue by tgp1994** [ZeeRooo/MaterialFBook#59]
Issue: App crashes when tapping the email button on the About section of any Page.
To reproduce:
1. In MaterialFB, navigate to any Page.
2. Go to the About section
3. If available, tap the email contact button. App crashes.

Expected result: MFB goes through the proper calls to dispatch an email. Meaning, either the prompt for selecting an email app opens, or the default email app opens up a blank email addressed to the correct recipient.

**Comment by ZeeRooo** [comment]
Mmm i see. Thank you for the request, it will be fixed soon as possible

**Comment by ZeeRooo** [comment]
I solved it in the **v3.2**

You can **download** the latest version from **here**: https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.2.0.apk

**Comment by tgp1994** [comment]
@ZeeRooo Thanks for keeping me posted! I've been using F-Droid in the past to download your app, do I need to manually download it now or will it still be updated there?

**Comment by ZeeRooo** [comment]
I dont know when F-Droid admins will update my app, maybe it can take few hours, days or week, depends on they build machine.
If you want use my app right now, download it from the link above
