### ISSUE TITLE
Add Pages to the Navigation menu items

### ISSUE THREAD

**Issue by notnsane** [ZeeRooo/MaterialFBook#60]
I mostly use Facebook for work, so I would really like this feature.

**Comment by ZeeRooo** [comment]
Like bookmarks?

**Comment by notnsane** [comment]
Hm, like it is for all the other things in the sidebar? Groups, Events, Photos, etc. Just add an option to show Pages there.

**Comment by ZeeRooo** [comment]
I added a navigation drawer _(in the right)_ where you can save bookmarks.

Please try the **v3.2** https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.2.0.apk
