### ISSUE TITLE
Web Themes Load After Data is Displayed

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#61]
If you set a Web Theme that is not the default then the color change lags behind the loading of the page. This is very clear in the MaterialAmoled theme where it loads with a white background then makes it black AFTER the data is displayed. Why not download the data, apply the theme, THEN display it? It would be much neater!

**Comment by ZeeRooo** [comment]
I improved the load themes method, please try with the **v3.2**

**Download:** https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.2.0.apk
