### ISSUE TITLE
Add Share URL Option

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#65]
I need a way to share the current URL while in the app.

This is especially true now that facebook broke the mobile version so it can't share events. I find myself looking at an event and wanting to give the facebook link to a friend but I can't see any way to do this. I used to long press on the event in the events list but this doesn't work anymore.

A share button up top that sends the current URL to an app would be awesome, or some way to see the URL so a copy and paste could happen, or a long press in the favorites right slide window! I didn't know this was there until recently!

I am thinking you could integrate this slide window with a share feature somehow where you can save AND share facebook links from there! You could add that star icon next to messages on the top to bookmark the favorite AND automatically open the window and then have a share icon next to the delete icon right there! Super intuitive this way and easy!

Thank you!

**Comment by ZeeRooo** [comment]
The fab button have a option to share the current url. Also share the
bookmark url is a good option too, im going to implement it in the next
update

**Comment by landry314** [comment]
Oh, no, I had the FAB turned off because I hate FABs but this one gets out of the way when you scroll which is nice. I am glad I know about this now.

I still think putting the favorites star on the top would be really cool to quickly mark a page for later use, and adding a share button next to the delete button in the favorites window would be also really convenient!

**Comment by creativetrendsapps** [comment]
@landry314 , wouldn't adding a share button to the bookmark drawer confuse the user? I think it would seem as though you'd be trying to share a bookmark and not the current page you're on.

**Comment by ZeeRooo** [comment]
Im going to implement the share button in bookmarks drawer  in the next
update. Im waiting to Facebook to aprove a new permission to share photos
and videos.

**Comment by landry314** [comment]
@creativetrendsapps, isn't that the same thing??

**Comment by ZeeRooo** [comment]
To share the bookmark url http://i.imgur.com/XuZ1cXV.png

**Comment by creativetrendsapps** [comment]
@landry314 So you'd like to share bookmarks that are already saved and not the current page you're on? Which is something different than you're asking for. 

Or, are you saying you'd like to save the current page you're on as a bookmark, then share that bookmark?

I'm asking because wouldn't that just be another step for more users? 

I get sharing a bookmark but... the two are different. From a UX stand point using the FAB would be better to share the current URL. 

Placing it in the bookmarks drawer (unless you want to share that bookmark), doesn't make much sense, but to each their own.

**Comment by landry314** [comment]
i like both options. i would like a share icon in the top bar that would share the current url, honestly. i find myself always wanting to do this and the url is not shown in this app like other browsers. i have been doing it with the FAB but i prefer it in the top bar is all i am saying, it would be easier.

i like the share next to the bookmarks too, why not? but this doesnt save TIME because i still have to make a bookmark first. i am trying to save time, i am always sharing events links... i always have to prune them too to get rid of the nonsense after the "?" in the url. if the url popped up within materialfbook and allowed me to edit and copy it there that would be even better for me, personally, now, i am sharing it to my clipboard app then editing it...

**Comment by ZeeRooo** [comment]
@landry314 it was added in the **v3.3**.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.3.0.apk
