### ISSUE TITLE
Change mandatory Facebook permissions request to optional

### ISSUE THREAD

**Issue by Bitim** [ZeeRooo/MaterialFBook#67]
When you want to connect to your FB account with MFB, the app asks for mandatory permissions for FB basic info, and friends list.

Please change this request from mandatory to optional, it's a privacy concern.
Thanks.

**Comment by ZeeRooo** [comment]
You are right, im going to delete those permissions on the next update.

**Comment by ZeeRooo** [comment]
Permission removed. See: https://github.com/ZeeRooo/MaterialFBook/commit/633fbdbc30d6696ef8c9ba36443459cf4632b919#diff-a46093c384cb3e780d1a4e8e814735f9L22

**Comment by Bitim** [comment]
The app still asking for basic info permission.

**Comment by ZeeRooo** [comment]
What is "basic info"?

**Comment by Bitim** [comment]
Basic profile, my mistake:
![screenshot_20170602-124530](https://cloud.githubusercontent.com/assets/4103710/26724444/1d475d0c-47a2-11e7-9d5b-db46e4ae437b.png)

And also post permission:
![screenshot_20170602-044851](https://cloud.githubusercontent.com/assets/4103710/26724449/2160d1de-47a2-11e7-8528-25e247a8f5d9.png)

I think MFB, should be only wrapper to FB with feature that are not depending on FB permissions.

**Comment by ZeeRooo** [comment]
- Publish_permissions: To share a photo from gallery, you can allow/deny
from FB settings.
- Link: To get your profile url when click in the photo.
- Cover: To get the cover photo and display it into the left menu.
- Id: To get your user id (used for the profile pic).
- Name: to get your user name and display it in the left menu.

**Comment by Bitim** [comment]
> - Link: To get your profile url when click in the photo. 
>- Cover: To get the cover photo and display it into the left menu. 
>- Id: To get your user id (used for the profile pic). 
>- Name: to get your user name and display it in the left menu.

I think these features are not worth the price of privacy. 

Anyway, it shouldn't be mandatory whatsoever.

**Comment by ZeeRooo** [comment]
Some permissions (like friendlist) were removed in the last version.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk

**Comment by Bitim** [comment]
@ZeeRooo it's not enough. All Facebook permissions should be **optional**, if users don't care about privacy, they can use the official Facebook app.

This features are only nice-to-have, and they are absoulotly not a necessity.
