### ISSUE TITLE
Add ability to open FB URLs from external apps in MFB

### ISSUE THREAD

**Issue by Bitim** [ZeeRooo/MaterialFBook#69]
Hi.
Now if you are trying to open FB URL with MFB, the app not redirect you too the URL, but to the main news feed page.
So practically you can open FB links from external sources.
Thanls.

**Comment by ZeeRooo** [comment]
I fixed it on profile and pages urls, can you send me a url?

**Comment by Bitim** [comment]
It doesn't matter which url. Any link not working. Links to profiles, pages, specific posts, specific comments, etc.

**Comment by ZeeRooo** [comment]
Working:
Pages, groups, like: https://m.facebook.com/warrobots/

Doesnt work: https://m.facebook.com/public/Roberto-Hernandez

https://m.facebook.com/profile.php?id=100010096601034

So, im going to work on this.

**Comment by Bitim** [comment]
So maybe it's releated to non-mobile link. Try this:
https://facebook.com/warrobots/

**Comment by ZeeRooo** [comment]
Its working too

**Comment by Bitim** [comment]
Not for me:
https://streamable.com/pqlrl

**Comment by ZeeRooo** [comment]
Its fixed on 3.1.0 +

**Comment by Bitim** [comment]
OK, but FYI latest version on F-droid is 2.9.

**Comment by ZeeRooo** [comment]
I dont know, i dont use fdroid. I know is very outdated. You can download
the apk from the repo ir XDA Labs

**Comment by Bitim** [comment]
So who is maintaining the F-droid version?

**Comment by ZeeRooo** [comment]
Fdroid developers. They update all the apps, no the app developer like in
Google Play.
