### ISSUE TITLE
Wrong package id

### ISSUE THREAD

**Issue by krt16s** [ZeeRooo/MaterialFBook#71]
You changed the package id in https://github.com/ZeeRooo/MaterialFBook/commit/8f1294713326cba2d17909c5211fb82c8bc661f4. This breaks updates for existing users, since for Android this is a completely new app. Was this an intended change?

**Comment by tgp1994** [comment]
That would explain why 2.9.0 is still the latest version on F-Droid (>1 month ago).

**Comment by ZeeRooo** [comment]
Maybe... I will revert the package id

**Comment by tgp1994** [comment]
3.2.0 is live on F- roid! Thanks ZeeRooo.

**Comment by krt16s** [comment]
That's because I forcefully rewrite package id on f-droids build: `prebuild=sed -i -e '/applicationId/s/me.zeerooo.materialfb/me.zeeroooo.materialfb/g' build.gradle`

**Comment by ZeeRooo** [comment]
Thank you so much @krt16s 👍

**Comment by Bitim** [comment]
@ZeeRooo I don't think @krt16s fixed the problem. It was one time workaround, you still need to revert the application ID.

**Comment by krt16s** [comment]
While the workaround will automatically applied to fdroid builds, I'd rather have a more mature solution. Iirc the problem is that @ZeeRooo die publish a build with the other package id elsewhere. So i think the only option to solve this more permanently will be build flavors. I think I can have a look at it.

**Comment by Bitim** [comment]
So why the new version of MFB is missing from F-droid repo?

**Comment by krt16s** [comment]
Because the update still has to be applied manually? And because the buildserver was going down for maintenance and we still try to squash some bugs.

**Comment by krt16s** [comment]
Build flavor: https://github.com/ZeeRooo/MaterialFBook/pull/80

Update: I also fails, because the gradle wrapper points to a to old gradle version. Fix is https://github.com/ZeeRooo/MaterialFBook/pull/81.  Again, update with workaround in fdroid is https://gitlab.com/fdroid/fdroiddata/commit/67467902, but I dont like piling up workarounds on our side, but rather get them apllied and fixed in upstream.
