### ISSUE TITLE
Notification for Messages

### ISSUE THREAD

**Issue by bdtoole** [ZeeRooo/MaterialFBook#73]
It's possible I've missed some information on this somewhere, but there seem to be occasional issues with notifications not coming through. In addition, I don't see any way to get immediate real-time notifications for messages.

I would love to use this as a Messenger replacement, but in my attempt to, I've had messages not send notifications as expected, and it looks like the most granular checking I can get is once a minute. I would much rather have instantaneous push notifications the way the actual Messenger app does.

Would this be possible to implement, and do you have any idea why the notifications don't come through sometimes? I'm on an LG G3 with Marshmallow, and I have set the app to ignore the Android Battery Optimizations.

**Comment by ZeeRooo** [comment]
We are using Alarm Mamager to schedule the "check notifications task".
Since API 19 (Kit Kat), Google limited the min. value for this API in 60
seconds (to limit the battery drain).
In other words, we cant sync the notifications in less time than 1 minute
(for now). Im going to see other way to schedule the notifications.
Sorry.

**Comment by bdtoole** [comment]
Makes sense. I saw a comment about a month ago somewhere from the Hermit Lite Apps developer saying they found a workaround for the Messenger notifications, but I have no idea what it is - not sure if you've ever been in contact with them, but it could be worth reaching out and asking!

Any thoughts on my issue where notifications just sometimes don't come through for messages? Unfortunately, I haven't been able to reproduce the error with any consistency - sometimes it just doesn't happen. I do have Messenger.com added as a web panel in my Vivaldi browser on my PC, so I'm wondering if for some reason, that picks up the message even when not in focus, and when your process checks, it doesn't see the message as "new" at that time. If that were the cause, though, I would think it would happen with every message, and not some some of the time.
