### ISSUE TITLE
Two bugs when playing videos

### ISSUE THREAD

**Issue by sha-265** [ZeeRooo/MaterialFBook#74]
1. The first bug is when playing non-wide ratio videos, the video is not centered (also I think the background color should be black). Screenshot:
![562eq2t](https://cloud.githubusercontent.com/assets/4103710/25773132/caab94a4-3280-11e7-98d4-134063419a7c.png)

2. The second bug is screen's orientation is forced to landscape mode, and only to specific side, while ignoring the screen's current orientation before playing the video. For example if I'm using MFB in portrait mode, and start playing a video the video will open in full screen mode while the screen orientation forced to be landscape mode. Also if I'm using MFB in the opposite landscape mode side and start playing a video the video will force the opposite landscape side and the the video will be upside down from user current perspective.

**Comment by ZeeRooo** [comment]
I fixed the orientation bug. But i never experienced the first bug. 

Try with the last version: https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.3.0.apk
