### ISSUE TITLE
Regression in 3.3.0: Start URL ignored.

### ISSUE THREAD

**Issue by nonno-cicala** [ZeeRooo/MaterialFBook#77]
MaterialFBook always starts on Most Recent even if I set anything else in "Start URL", it worked in 3.2.0.

**Comment by landry314** [comment]
this is causing me to downgrade. i'm back to 3.2.0 i just cant deal with this.

**Comment by ZeeRooo** [comment]
Fixed in v3.4.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk
