### ISSUE TITLE
Hide Menu Bar Not Working on EVENTS PAGE in 3.3.0

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#78]
Yeah, "Hide Menu bar" is on in the settings but on the events page I still see the menu bar. I have only found it on the events page so far for some reason.

**Comment by ZeeRooo** [comment]
I think its fixed on the last version. Anyway tell me if the inconvenient continue.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk

**Comment by ZeeRooo** [comment]
Its because we need the bar to "publish" and "cancel" buttons.

**Comment by landry314** [comment]
this is still an issue in 3.4.0. when you go from the events link on the sidebar the menu bar is there but if you reload the events page when you are on it then the menu bar disappears as it should.

of course i am talking about when "Hide menu bar" is enabled.

**Comment by landry314** [comment]
oh i see it is intentional... hmm...
