### ISSUE TITLE
Feature: Notifications filter by type

### ISSUE THREAD

**Issue by Znuff** [ZeeRooo/MaterialFBook#84]
I am an administrator for a lot of pages, for example, but I don't actively manage them (someone else takes care of them). Unfortunately the Page settings don't have fine grain notification settings - you can't disable them per person, just per page. This results in a lot of notifications that I don't really care for my device to play a sound notification, for example.

Also, while I really want to get notifications and a sound on my device for Comments/Replies to my Posts/Other Comments, I really don't care if someone Liked my post in particular.

The notifications UI on the mobile website are of different types.

It would be very nice to be able to filter them by type, at least.

The link `a.touchable`'s `href` attribute contains a parameter called `notif_t=`.

I've digged trough all the ones I was able to find, and this is the list of them:

	notif_t=close_friend_activity -> friend in "close friends" group posted something.
	notif_t=like -> you/your pages have received a like
	notif_t=feedback_reaction_generic -> same as above, someone reacted to a post/comment etc.
	notif_t=event_aggregate -> notification about events
	notif_t=feed_comment_reply -> someone replied to your comment
	notif_t=page_message -> a page you manage has received a private message
	notif_t=page_user_activity -> weekly/daily page stats (new views, likes etc.)
	notif_t=review_audience_suggestions -> someone suggested page modifications that you need to review (change address, update contact data etc.)
	notif_t=page_reengaged -> a page you follow has posted after a long time
	notif_t=video_processed -> your video/gif upload is ready
	notif_t=page_fan -> a pge you manage has new likes
	notif_t=plan_user_invited -> you have been invited to an event
	notif_t=japan_ci_friends_suggestion -> one of your contacts is now on facebook
	notif_t=aymt_events_after_event_engagement_tip -> your page event has ended, share what happened
	notif_t=share_reply -> edited their comment on their link (?)
	notif_t=feed_comment -> someone commented on your post
	notif_t=page_review_reminder -> reminder to review a place/page you've checked in

**Comment by ZeeRooo** [comment]
Thank you, good idea! Also the badge in launcher.

**Comment by ZeeRooo** [comment]
Feature added in v3.6.0.
https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_3.6.0.apk?raw=true
