### ISSUE TITLE
it's doing nothing, only white screen

### ISSUE THREAD

**Issue by sotitrox** [ZeeRooo/MaterialFBook#86]
Hello I have a tablet samsung sm-t560, and I just install m fbook and it's doing nothing only white screen.
![tmp_31353-screenshot_2017-05-25-01-55-39-1298343653](https://cloud.githubusercontent.com/assets/8594436/26437762/fe367c24-40ec-11e7-9e93-2e8b5d781d5e.png)
![tmp_31353-screenshot_2017-05-25-01-55-331994828973](https://cloud.githubusercontent.com/assets/8594436/26437764/023bf7cc-40ed-11e7-893c-a8b5ec8fb05e.png)

**Comment by Thinksamoral** [comment]
I have noticed this too. Reverted to the official app for now.

I'm on an S7 Edge on Nougat.

**Comment by bradley-e-smith** [comment]
+1 on my HTC M8 on Sense 6 stock ROM with Magisk installed

**Comment by ZeeRooo** [comment]
Please try with the v3.4 and tell me if the issue continue. 

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk

Sorry for the inconvenient.

**Comment by sotitrox** [comment]
Now its working gor me, thanks so much

**Comment by ZeeRooo** [comment]
Cool :)
