### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by Androidfast** [ZeeRooo/MaterialFBook#87]
When you open the application for the first time gives error. Invalid key hash. The key hash G7oKicqwZwV6eGCLzxCZSj9PaAc= does not match any stored key hashes. Configure your app key hashes at https://developers.facebook.com/apps/1440102826005611/

**Comment by moso** [comment]
Same here

`Invalid key hash. The key hash G7oKicqwZwV6eGCLzxCZSj9PaAc= does not match any stored key hashes. Configure your app key hashes at https://developers.facebook.com/apps/1440102826005611/`

**Comment by ZeeRooo** [comment]
Please try with the v3.4 and tell me if the issue continue. Sorry for the inconvenient.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk
