### ISSUE TITLE
Crashes when delete bookmark

### ISSUE THREAD

**Issue by monopatis** [ZeeRooo/MaterialFBook#88]
When I try to delete a bookmark from right slide panel, it crashes. v3.3.0

**Comment by ZeeRooo** [comment]
Please try with the new version and tell me.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk

Sorry for the inconvenient.

**Comment by monopatis** [comment]
Its ok on this version.  Thanks
