### ISSUE TITLE
F-Droid doesn't have 3.4.1

### ISSUE THREAD

**Issue by tgp1994** [ZeeRooo/MaterialFBook#92]
The [F-Droid wiki](https://f-droid.org/wiki/index.php?title=me.zeeroooo.materialfb&redirect=no#Versions) states that their repository does not have version 3.4.1 yet, despite it being available for several weeks now. The message is:

> We don't have the current version of this app.  (Check mode: RepoManifest) (Auto-update mode: None)
> The current (recommended) version is 3.4.1 (version code 49).

I thought F-Droid was supposed to automatically build from the source code, but maybe something needs to be submitted first?

**Comment by Bitim** [comment]
It's probably because @ZeeRooo changed the app's ID, as mentioned here: https://github.com/ZeeRooo/MaterialFBook/issues/71. @krt16s made some workaround, but it seems that @ZeeRooo, didn't fixed it as he should.

**Comment by tgp1994** [comment]
Ah, I do remember commenting there, I didn't know the issue was ongoing... Sorry for the duplication of reports!

**Comment by Bitim** [comment]
I'm not sure this issue still ongoing. Maybe it's some other problem.

**Comment by mimi89999** [comment]
@ZeeRooo Can you please tag releases?
