### ISSUE TITLE
Sidebar is empty, just shows Settings

### ISSUE THREAD

**Issue by spectromas** [ZeeRooo/MaterialFBook#94]
I've been using this app for a while so I know what the sidebar should look like but I've just done a reset on my phone and after reinstalling materialfbook the sidebar only has my name and settings. 
I installed from fdroid but noticed there was a newer version here so installed the latest apk but it didn't make any difference. 
How can I get the rest of the entries back?

**Comment by ZeeRooo** [comment]
Configure the shorcuts in settings

**Comment by spectromas** [comment]
Ok thanks. I checked and they were all enabled but it seems exiting the menu after checking caused them to all appear.
