### ISSUE TITLE
Notifications Issues

### ISSUE THREAD

**Issue by creativetrendsapps** [ZeeRooo/MaterialFBook#98]
Notifications seemed to have stopped working. The error is in the last check of the notification when it's trying to display the users image. The bitmap is returning null with bitmap getWidth on a null object reference.

**Comment by creativetrendsapps** [comment]
The problem seems to be that Facebook has changed something with the sender of the notifications image. It's the same div and image class but something else has changed.

**Comment by ZeeRooo** [comment]
Mmm ok. I'll see later. Thank you!

El jul. 21, 2017 10:03, "Jorell Rutledge" <notifications@github.com>
escribió:

The problem seems to be that Facebook has changed something with the sender
of the notifications image. It's the same div and image class but something
else has changed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/98#issuecomment-316995292>,
or mute the thread

**Comment by creativetrendsapps** [comment]
@ZeeRooo what I did was just remove the sender's profile picture for the moment.

**Comment by ZeeRooo** [comment]
It looks like Facebook has been changed the url (encoded or anything similar). 

`<i class="img profpic" aria-label="J-Snipper Wf" role="img" style="background:#d8dce6 url(&quot;https\3a //scontent.faep4-1.fna.fbcdn.net/v/t1.0-1/cp0/e15/q65/c13.0.43.43/p43x43/17952529_440349089644974_8295842265395554640_n.jpg?efg\3d eyJpIjoidCJ9\26 oh\3d 6c2415c8bb56671ca7ea3346cbdaf861\26 oe\3d 5A38EA6E&quot;) no-repeat center;background-size:100% 100%;-webkit-background-size:100% 100%;width:43px;height:43px;" data-sigil="profile_image"></i>`

**Comment by creativetrendsapps** [comment]
@ZeeRooo isn't it the same image class being selected in jsoup?

**Comment by ZeeRooo** [comment]
Yes it is but right now the url in encoded or similar because if you copy
and paste this url in the browser, the image isn't avaible.

El jul. 25, 2017 10:44, "Jorell Rutledge" <notifications@github.com>
escribió:

@ZeeRooo <https://github.com/zeerooo> isn't it the same image class being
selected in jsoup?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/98#issuecomment-317741512>,
or mute the thread

**Comment by creativetrendsapps** [comment]
Oh, so they're encrypting the image? That's strange. I wonder why?

**Comment by ZeeRooo** [comment]
Who knows... but is very easy to decode. Im working on this, later i will upload the patch. Just replace some characters.

**Comment by creativetrendsapps** [comment]
Do you notice when using the Alarm manager notifications aren't checked or fetched by the time the user has then set within the settings menu? They're delayed a bit. Like for instance, a user can set their interval for 30mins & won't be notified for close to an hour. It's strange, lol. I switched back to using a Handler for the time being.

**Comment by creativetrendsapps** [comment]
Do you notice when using the Alarm manager notifications aren't checked or fetched by the time the user has then set within the settings menu? They're delayed a bit. Like for instance, a user can set their interval for 30mins & won't be notified for close to an hour. It's strange, lol. I switched back to using a Handler for the time being.

**Comment by ZeeRooo** [comment]
I know since API 19 Alarmmanager is inexact but its strange.... lol

**Comment by ZeeRooo** [comment]
@creativetrendsapps  Look at this :)

https://scontent.faep4-1.fna.fbcdn.net/v/t34.0-12/20293043_850988211718908_6633889421712347793_n.jpg?oh=4e1c5280233de37e410421dd27769b06&oe=597A51BF

**Comment by creativetrendsapps** [comment]
Cool you fixed it.

**Comment by ZeeRooo** [comment]
Yep, enjoy.

**Comment by creativetrendsapps** [comment]
Hey, there's an arrayindexoutofbounds crash only when checking for messages. It's caught by still can cause a crash in the onhandleintent method for checking notifications. It's happening with the split method for notification profile picture checking. java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

**Comment by ZeeRooo** [comment]
Mmm.. i dont know, i dont have crashes or issues :/

**Comment by ZeeRooo** [comment]
Maybe its caused by the string.split used to copy the url from styles. I
dont know if i can avoid this part and get the url inside of a style
directly with jsoup.

**Comment by creativetrendsapps** [comment]
I'm looking into it. I don't have crashes either but, there was an issue with it in one of my apps earlier in the Play Store. I fixed with a try catch but I really don't want to use that, lol. Once I fix the error I'll send you a pull request.

**Comment by ZeeRooo** [comment]
Ok, thank you and good luck.

**Comment by ZeeRooo** [comment]
@creativetrendsapps Have been you tried with:

`if (!pictureStyle.isEmpty())
                    splitUrl(pictureStyle, false);`

and delete the try - catch from splitUrl?

**Comment by creativetrendsapps** [comment]
@ZeeRooo not sure that will fix the  java.lang.ArrayIndexOutOfBoundsException: length=1; index=1, because the split has an index of 1 and length of 1. This is happening because the index starts at 1 and shouldn't it should start a 0 and be expanded.

**Comment by creativetrendsapps** [comment]
@ZeeRooo that seems to have gotten rid of the java.lang.ArrayIndexOutOfBoundsException: length=1; index=1, exception. Though I'm still testing.

**Comment by creativetrendsapps** [comment]
@ZeeRooo now there's a nullpointerexception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference. There's something going on with the message check. That's the only issue. I'll see if I can get the split to get fixed and these issues should stop.

**Comment by ZeeRooo** [comment]
I get ArrayIndexOutOfBoundsException only when pictureStyle is null (no messages or notifications). So, i added 

> if (pictureStyle  != null)
or
> if (!pictureStyle .isEmpty)

And solve the problem. And i think the NullPointerException is caused by the same null pictureStyle.

**Comment by creativetrendsapps** [comment]
This should be re-opened as Facebook has messed up notifications again.

**Comment by pieterdavid** [comment]
I have been trying MaterialFBook over the last couple of days (great app, thanks a lot!), and also ran into this (or a very related) issue... any notification crashes with
```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at me.zeeroooo.materialfb.Notifications.NotificationsService.a(Unknown Source)
	at me.zeeroooo.materialfb.Notifications.NotificationsService.b(Unknown Source)
	at me.zeeroooo.materialfb.Notifications.NotificationsService.onHandleIntent(Unknown Source)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```
(version B-3.5.0 from F-Droid)

**Comment by creativetrendsapps** [comment]
The string split should be 0 instead of the 1 that's used. That fixes the crash though the image still is unavailable.

**Comment by ZeeRooo** [comment]
I had some exams recently + no computer. But right now im working to fix
the notification system.
Thank you for the support! I will update this code soon as possible.

**Comment by singulararmchair** [comment]
FWIW, notifications were working for me on an old CyanogenMod phone, but completely stopped once I upgraded to LineageOS 13. I've tried with various older versions of your app, and none of them seem to give notifications.

**Comment by tgp1994** [comment]
I think this issue may need to be reopened. Notifications have not been working for me, for several days now. MFB does not seem to detect status or message notifications in the app either.

**Comment by creativetrendsapps** [comment]
@tgp1994 the notification badges are separate from receiving notifications. @ZeeRooo are you able to work on this? I can send you some code via a gist if you'd like. I'd do a pull request but I'm not too sure how you're redoing your app (as you said before).

**Comment by ZeeRooo** [comment]
I fixed all the issues. I have to update the code. I'll do it when i finish
the migration from AlarmManager to JobScheduler for compatibility with Oreo.

**Comment by creativetrendsapps** [comment]
@ZeeRooo cool. Hopefully, JobScheduler is more consistent than the AlarmManager.

**Comment by ZeeRooo** [comment]
Maybe, but is a little difficult set a time to repeat the task.
*.setPeriodic* works well on pre-Nougat but doesn't respect if there's or
no a connection avaible (*setRequiredNetworkType*). The only way to do it
in Lollipop+ is .*setMinimumLatency (min interval) *with
*.setOverrideDeadline* (max interval) (this because the task can take more
time than the declared in *setMinimumLatency*, but *setOverrideDeadline*
also ignores the *setRequiredNetworkType*). And i don't want to use 3rd
party libraries to schedule a simple task...

2017-12-04 14:01 GMT-03:00 Jorell Rutledge <notifications@github.com>:

**Comment by tgp1994** [comment]
@creativetrendsapps Indeed, that's why I commented initially - neither are working within this app now.

@ZeeRooo When you say you fixed all of the issues, were you referring to the recent one I had just posted as well?

**Comment by ZeeRooo** [comment]
Im talking about a new version that im working on. I'll upload it in a few
days, im on holidays right now so i can work

**Comment by creativetrendsapps** [comment]
@ZeeRooo , the Evernote jobscheduler looks good and easy to implement. It's too many background restrictions though so I didn't stick with it myself. However, if you decide to stick with your current notification system, I've fixed bot the crashes and not being able to grab the users profile picture. I can do a pull request if you'd like, let me know.

**Comment by ZeeRooo** [comment]
Thank you Jorrel. Tomorrow I'll upload a new version with bugfixes, and
other things.
I'm using firebase jobdispatcher instead android-job from Evernote because
is the official alternative to the joke-JobScheduler.

El dic. 12, 2017 16:16, "Jorell Rutledge" <notifications@github.com>
escribió:

@ZeeRooo <https://github.com/zeerooo> , the Evernote jobscheduler looks
good and easy to implement. It's too many background restrictions though so
I didn't stick with it myself. However, if you decide to stick with your
current notification system, I've fixed bot the crashes and not being able
to grab the users profile picture. I can do a pull request if you'd like,
let me know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/98#issuecomment-351161057>,
or mute the thread

**Comment by ZeeRooo** [comment]
Thank you @creativetrendsapps . Tomorrow I'll upload a new version with bugfixes, and
other things.
I'm using firebase jobdispatcher instead android-job from Evernote because
is the official alternative to the joke-JobScheduler.
PS: Can i ask for your OS version?

**Comment by creativetrendsapps** [comment]
@ZeeRooo I have several OS versions. My main device is on Nougat while one of my test devices is running Oreo.

**Comment by creativetrendsapps** [comment]
Good job with the job scheduler. There are a few issues, however. 1, the job service is never started until you include this in your jobservice:

@Override
    public boolean onStartJob(JobParameters job) {
        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        Log.i("JobService_MFB", "Started");
        if(preferences.getBoolean("notif", false)) {
            NotificationsJIS.enqueueWork(this, new Intent(this, NotificationsJIS.class).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));
        }
        return false;
    } 

2, Message notifications do not post as there is a timeout exception when checking for messages.

12-14 08:18:11.279 20753-21554/me.zeeroooo.materialfb W/System.err: java.net.SocketTimeoutException: Read timeout
12-14 08:18:11.279 20753-21554/me.zeeroooo.materialfb W/System.err:     at org.jsoup.internal.ConstrainableInputStream.read(ConstrainableInputStream.java:58)
12-14 08:18:11.279 20753-21554/me.zeeroooo.materialfb W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:107)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at org.jsoup.internal.ConstrainableInputStream.readToByteBuffer(ConstrainableInputStream.java:87)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:169)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:103)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:832)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at org.jsoup.helper.HttpConnection.get(HttpConnection.java:289)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at me.zeeroooo.materialfb.Notifications.NotificationsJIS.SyncNotifications(NotificationsJIS.java:103)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at me.zeeroooo.materialfb.Notifications.NotificationsJIS.onHandleWork(NotificationsJIS.java:70)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-14 08:18:11.280 20753-21554/me.zeeroooo.materialfb W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-14 08:18:11.281 20753-21554/me.zeeroooo.materialfb W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by landry314** [comment]
I've gotten a notification about 2 times in my life... right after installing it I believe. I don't know for how many people notifications actually work.
